name: 'Build Docker Image'
description: 'Builds and pushes Docker image with caching'

inputs:
  app_path:
    description: 'Path to app directory'
    required: true
  context:
    description: 'Docker build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Read marker configuration
      id: config
      shell: bash
      working-directory: ${{ inputs.app_path }}
      run: |
        PROJECT=$(grep "^project:" superdeploy | cut -d: -f2 | xargs)
        APP=$(grep "^app:" superdeploy | cut -d: -f2 | xargs)
        VM_ROLE=$(grep "^vm:" superdeploy | cut -d: -f2 | xargs)
        
        echo "project=$PROJECT" >> $GITHUB_OUTPUT
        echo "app=$APP" >> $GITHUB_OUTPUT
        echo "vm_role=$VM_ROLE" >> $GITHUB_OUTPUT
        
        echo "✅ Config: project=$PROJECT, app=$APP, vm=$VM_ROLE"
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_TOKEN }}
    
    - name: Determine Dockerfile path
      id: dockerfile
      shell: bash
      run: |
        if [ -n "${{ inputs.dockerfile }}" ]; then
          DOCKERFILE="${{ inputs.dockerfile }}"
        else
          DOCKERFILE="./${{ inputs.app_path }}/Dockerfile"
        fi
        echo "path=$DOCKERFILE" >> $GITHUB_OUTPUT
        echo "📝 Using Dockerfile: $DOCKERFILE"
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ steps.dockerfile.outputs.path }}
        push: true
        tags: |
          ${{ env.DOCKER_ORG }}/${{ steps.config.outputs.app }}:latest
          ${{ env.DOCKER_ORG }}/${{ steps.config.outputs.app }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.DOCKER_ORG }}/${{ steps.config.outputs.app }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_ORG }}/${{ steps.config.outputs.app }}:buildcache,mode=max

outputs:
  project:
    description: 'Project name'
    value: ${{ steps.config.outputs.project }}
  app:
    description: 'App name'
    value: ${{ steps.config.outputs.app }}
  vm_role:
    description: 'VM role'
    value: ${{ steps.config.outputs.vm_role }}

