core_secrets_used: false
merged_at: '2025-10-22T13:25:51.328833'
repo: cheapaio/api
secrets:
  API_SECRET_KEY: RANDOM_32_CHARS_API_KEY
  DATABASE_URL: postgresql://superdeploy:SuperSecure123Pass@postgres:5432/superdeploy_db
  ENVIRONMENT: production
  PROXY_REGISTRY_API_KEY: RANDOM_32_CHARS_PROXY_KEY
  PROXY_REGISTRY_URL: http://proxy-registry:8001
  RABBITMQ_URL: amqp://superdeploy:SuperSecure123Pass@rabbitmq:5672/
source_env: /Users/cfkarakulak/Desktop/cheapa.io/hero/app-repos/api/.env
