"""Orchestrator config.yml template generator"""

import yaml


def generate_orchestrator_config(
    gcp_project: str,
    region: str,
    zone: str,
    ssl_email: str,
    docker_subnet: str,
) -> str:
    """Generate formatted orchestrator config.yml content"""

    orchestrator_config = {
        "project": {
            "name": "orchestrator",
            "ssl_email": ssl_email,
        },
        "gcp": {
            "project_id": gcp_project,
            "region": region,
            "zone": zone,
        },
        "ssh": {
            "key_path": "~/.ssh/superdeploy_deploy",
            "public_key_path": "~/.ssh/superdeploy_deploy.pub",
            "user": "superdeploy",
        },
        "vm": {
            "name": "orchestrator",
            "machine_type": "e2-medium",
            "disk_size": 50,
        },
        "network": {
            "vpc_name": "superdeploy-network",
            "subnet_cidr": "10.128.0.0/20",
            "docker_subnet": docker_subnet,
        },
        "grafana": {
            "domain": "",
            "port": 3000,
            "smtp_enabled": False,
            "smtp_host": "",
            "smtp_user": "",
        },
        "prometheus": {
            "domain": "",
            "port": 9090,
            "retention": "15d",
        },
        "caddy": {
            "enabled": False,
            "version": "2-alpine",
            "http_port": 80,
            "https_port": 443,
            "admin_port": 2019,
        },
    }

    # Build formatted YAML with comments
    yml_lines = []
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Orchestrator Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Auto-generated by: superdeploy orchestrator init")
    yml_lines.append("# Then run: superdeploy orchestrator up")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Project Information")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"project": orchestrator_config["project"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Cloud Provider Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"gcp": orchestrator_config["gcp"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# SSH Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"ssh": orchestrator_config["ssh"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# VM Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"vm": orchestrator_config["vm"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Network Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"network": orchestrator_config["network"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Monitoring Configuration (Global - All Projects)")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        "# Grafana and Prometheus run on orchestrator VM and monitor ALL projects"
    )
    yml_lines.append(
        "# Configure a single domain for global access (e.g., grafana.yourdomain.com)"
    )
    yml_lines.append("# All projects will be visible in Grafana with project filtering")
    yml_lines.append("")
    yml_lines.append("# Grafana Configuration")
    yml_lines.append(
        yaml.dump(
            {"grafana": orchestrator_config["grafana"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append(
        "# Alert notification settings (optional - configure in Grafana UI)"
    )
    yml_lines.append(
        "# Variables: GRAFANA_ADMIN_USER, GRAFANA_ADMIN_PASSWORD, GRAFANA_SMTP_PASSWORD (from secrets.yml)"
    )
    yml_lines.append("")
    yml_lines.append("# Prometheus Configuration")
    yml_lines.append(
        yaml.dump(
            {"prometheus": orchestrator_config["prometheus"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Caddy Configuration (Reverse Proxy for HTTPS)")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"caddy": orchestrator_config["caddy"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")

    return "\n".join(yml_lines)
