"""Project secrets.yml template generator"""


def generate_project_secrets(
    project_name: str,
    app_names: list,
    postgres_password: str,
    rabbitmq_password: str,
) -> str:
    """Generate formatted project secrets.yml content"""

    yml_lines = []

    # Header
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(f"# {project_name} - Secrets Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(f"# Auto-generated by: superdeploy {project_name}:init")
    yml_lines.append(f"# Edit secrets, then run: superdeploy {project_name}:validate")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("#")
    yml_lines.append("# ⚠️  SECURITY WARNING: This file contains sensitive credentials!")
    yml_lines.append("#    - DO NOT commit this file to Git")
    yml_lines.append("#    - Keep restrictive file permissions (600)")
    yml_lines.append("#    - Store securely in password manager/vault")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("")

    # Shared Secrets Section
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Shared Secrets")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Available to all applications in this project")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("secrets:")
    yml_lines.append("  shared:")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Database Configuration (Auto-generated)")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append(
        "    POSTGRES_HOST: ''    # Auto-filled with VM internal IP after 'superdeploy project:up'"
    )
    yml_lines.append("    POSTGRES_PORT: '5432'")
    yml_lines.append(f"    POSTGRES_USER: {project_name}_user")
    yml_lines.append(f"    POSTGRES_PASSWORD: {postgres_password}")
    yml_lines.append(f"    POSTGRES_DB: {project_name}_db")
    yml_lines.append("")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Message Queue Configuration (Auto-generated)")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append(
        "    RABBITMQ_HOST: ''    # Auto-filled with VM internal IP after 'superdeploy project:up'"
    )
    yml_lines.append("    RABBITMQ_PORT: '5672'")
    yml_lines.append(f"    RABBITMQ_USER: {project_name}_user")
    yml_lines.append(f"    RABBITMQ_PASSWORD: {rabbitmq_password}")
    yml_lines.append("")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Infrastructure")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append(
        "    ORCHESTRATOR_IP: ''  # Auto-filled after 'superdeploy orchestrator:up'"
    )
    yml_lines.append("")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Docker Registry Credentials")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Required for building and deploying container images")
    yml_lines.append("    # Get token from: https://hub.docker.com/settings/security")
    yml_lines.append("    DOCKER_REGISTRY: 'docker.io'  # Docker registry URL")
    yml_lines.append("    DOCKER_ORG: ''        # Docker Hub organization/username")
    yml_lines.append("    DOCKER_USERNAME: ''   # Your Docker Hub username")
    yml_lines.append(
        "    DOCKER_TOKEN: ''      # Docker Hub access token (NOT password)"
    )
    yml_lines.append("")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # SMTP Configuration (Email Notifications)")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Optional: Used for system alerts and notifications")
    yml_lines.append(
        "    SMTP_HOST: 'smtp.gmail.com'  # Gmail SMTP (or use smtp.sendgrid.net, etc.)"
    )
    yml_lines.append("    SMTP_PORT: '587'     # 587 (TLS), 465 (SSL), or 25 (plain)")
    yml_lines.append("    SMTP_USER: ''        # SMTP username (usually your email)")
    yml_lines.append(
        "    SMTP_PASSWORD: ''    # SMTP password or app-specific password"
    )
    yml_lines.append("    SMTP_FROM: ''        # From email address")
    yml_lines.append("")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # GitHub Integration (REQUIRED)")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append(
        "    # GitHub Personal Access Token for CI/CD and runner management"
    )
    yml_lines.append("    # Get token from: https://github.com/settings/tokens")
    yml_lines.append(
        "    # Required scopes: repo, workflow, admin:org (manage_runners)"
    )
    yml_lines.append(
        "    GITHUB_TOKEN: ''           # GitHub Personal Access Token (REQUIRED)"
    )
    yml_lines.append("    #   This token is used to:")
    yml_lines.append("    #   - Push code to private repositories")
    yml_lines.append("    #   - Trigger GitHub Actions workflows")
    yml_lines.append("    #   - Auto-generate runner registration tokens via API")
    yml_lines.append("")
    yml_lines.append(
        "    PRIVATE_REPO_TOKEN: ''     # GitHub PAT for private repo access in workflows"
    )
    yml_lines.append("    #   Required scope: repo (full control of private repos)")
    yml_lines.append("    #   Used by GitHub Actions to checkout private repositories")
    yml_lines.append("")

    # App-Specific Secrets Section
    yml_lines.append("  # " + "=" * 75)
    yml_lines.append("  # Application-Specific Secrets")
    yml_lines.append("  # " + "=" * 75)
    yml_lines.append("  # Add secrets that are only needed by specific applications")
    yml_lines.append("  # Example: API_KEY: 'xyz123', STRIPE_SECRET: 'sk_test_...'")
    yml_lines.append("  # " + "=" * 75)
    for app_name in app_names:
        yml_lines.append(f"  {app_name}: {{}}")
    yml_lines.append("")

    # Environment Aliases Section
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Environment Variable Aliases")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Map framework-specific variable names to secrets defined above")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("#")
    yml_lines.append("# Format:")
    yml_lines.append("#   ALIAS_NAME: SECRET_NAME")
    yml_lines.append("#")
    yml_lines.append("# Rules:")
    yml_lines.append(
        "#   - UPPERCASE value = reference to secret (e.g., DB_HOST: POSTGRES_HOST)"
    )
    yml_lines.append(
        "#   - lowercase/mixed = static value (e.g., API_URL: http://10.1.0.2:8000)"
    )
    yml_lines.append("#")
    yml_lines.append("# Examples:")
    yml_lines.append("#")
    yml_lines.append("#   Python/Cara Framework:")
    yml_lines.append("#     DB_HOST: POSTGRES_HOST")
    yml_lines.append("#     DB_PORT: POSTGRES_PORT")
    yml_lines.append("#     DB_USERNAME: POSTGRES_USER")
    yml_lines.append("#     DB_PASSWORD: POSTGRES_PASSWORD")
    yml_lines.append("#     DB_DATABASE: POSTGRES_DB")
    yml_lines.append("#")
    yml_lines.append("#   Next.js:")
    yml_lines.append("#     NEXT_PUBLIC_API_URL: http://10.1.0.2:8000")
    yml_lines.append("#     DATABASE_URL: POSTGRES_HOST")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("env_aliases:")
    for app_name in app_names:
        yml_lines.append(f"  {app_name}: {{}}")
    yml_lines.append("")

    return "\n".join(yml_lines)
