name: âš™ï¸ Ansible Configuration

on:
  push:
    branches:
      - master
    paths:
      - 'ansible/**'
  workflow_dispatch:
    inputs:
      target:
        description: 'Target VMs'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - system-base
          - app-deployment
          - git-server
          - scrape-workers
          - proxy-servers
          - full-core

jobs:
  ansible:
    runs-on: self-hosted
    
    steps:
      - name: ðŸ“¦ Checkout code
        run: |
          cd /opt/superdeploy
          git fetch origin
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
          echo "âœ… Code checked out: $(git rev-parse --short HEAD)"

      - name: ðŸ”§ Setup Ansible
        run: |
          if ! command -v ansible &> /dev/null; then
            echo "ðŸ“¥ Installing Ansible..."
            sudo apt-get update -qq
            sudo apt-get install -y ansible
          fi
          ansible --version

      - name: ðŸ“ Generate Ansible inventory
        run: |
          cd /opt/superdeploy/ansible
          
          # Use current IPs from Forgejo variables (NO FALLBACKS!)
          cat > inventories/dev.ini << EOF
          # Auto-generated by Forgejo Actions
          # REQUIRED: Set CORE_EXTERNAL_IP, SCRAPE_EXTERNAL_IP, PROXY_EXTERNAL_IP in Forgejo vars
          
          [core]
          vm-core-1 ansible_host=${{ vars.CORE_EXTERNAL_IP }} ansible_user=superdeploy
          
          [scrape]
          vm-scrape-1 ansible_host=${{ vars.SCRAPE_EXTERNAL_IP }} ansible_user=superdeploy
          
          [proxy]
          vm-proxy-1 ansible_host=${{ vars.PROXY_EXTERNAL_IP }} ansible_user=superdeploy
          
          [all:vars]
          ansible_python_interpreter=/usr/bin/python3
          ansible_become=yes
          ansible_become_method=sudo
          ansible_ssh_private_key_file={{ lookup('env', 'ANSIBLE_SSH_KEY') }}
          EOF
          
          echo "âœ… Inventory generated"

      - name: ðŸš€ Run Ansible playbook
        run: |
          cd /opt/superdeploy/ansible
          
          TARGET="${{ github.event.inputs.target || 'all' }}"
          
          echo "ðŸŽ¯ Deploying to: $TARGET"
          
          if [ "$TARGET" = "all" ]; then
            ansible-playbook -i inventories/dev.ini playbooks/site.yml
          else
            ansible-playbook -i inventories/dev.ini playbooks/site.yml --tags "$TARGET"
          fi

      - name: âœ… Verify deployment
        run: |
          cd /opt/superdeploy/ansible
          
          echo "â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—"
          echo "â•‘  ðŸ“Š Deployment Verification                                  â•‘"
          echo "â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•"
          echo ""
          
          echo "=== CORE VM ==="
          ansible core -i inventories/dev.ini -m shell -a "docker compose -f /opt/superdeploy/compose/docker-compose.yml ps" || true
          
          echo ""
          echo "=== SCRAPE VM ==="
          ansible scrape -i inventories/dev.ini -m shell -a "docker compose -f /opt/superdeploy/compose/docker-compose.yml ps" || true
          
          echo ""
          echo "=== PROXY VM ==="
          ansible proxy -i inventories/dev.ini -m shell -a "docker compose -f /opt/superdeploy/compose/docker-compose.yml ps" || true

      - name: ðŸŽ‰ Configuration Summary
        run: |
          echo ""
          echo "âœ… Ansible configuration completed!"
          echo "ðŸ“ Commit: ${{ github.sha }}"
          echo "ðŸ‘¤ Author: ${{ github.actor }}"
          echo "â° Time: $(date)"

