name: Deploy CORE Services

on:
  workflow_dispatch:
    inputs:
      api_image_tag:
        description: 'API Docker Image Tag'
        required: false
        default: 'latest'
      dashboard_image_tag:
        description: 'Dashboard Docker Image Tag'
        required: false
        default: 'latest'
      services_image_tag:
        description: 'Services Docker Image Tag'
        required: false
        default: 'latest'

jobs:
  deploy:
    runs-on: [self-hosted, core, linux, docker]
    
    steps:
      - name: ðŸ“¦ Checkout superdeploy code
        run: |
          cd /opt/superdeploy
          git config --global --add safe.directory /opt/superdeploy
          git fetch origin
          git reset --hard origin/master
          echo "âœ… Superdeploy code updated"

      - name: ðŸ“ Setup app .env files from Forgejo Secrets
        run: |
          mkdir -p /opt/app-repos/{api,dashboard,services}
          
          echo "Generating .env files from Forgejo Secrets..."
          
          # API .env
          cat > /opt/app-repos/api/.env <<EOF
          # Database
          DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.POSTGRES_DB }}
          
          # RabbitMQ
          RABBITMQ_URL=amqp://${{ secrets.RABBITMQ_USER }}:${{ secrets.RABBITMQ_PASSWORD }}@rabbitmq:5672/
          
          # API Config
          API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}
          ENVIRONMENT=production
          
          # Optional
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          
          # Proxy Registry
          PROXY_REGISTRY_URL=http://proxy-registry:8001
          PROXY_REGISTRY_API_KEY=${{ secrets.PROXY_REGISTRY_API_KEY }}
          EOF
          
          # Dashboard .env
          cat > /opt/app-repos/dashboard/.env <<EOF
          PUBLIC_URL=${{ secrets.PUBLIC_URL }}
          API_BASE_URL=${{ secrets.API_BASE_URL }}
          ENVIRONMENT=production
          EOF
          
          # Services .env
          cat > /opt/app-repos/services/.env <<EOF
          # Database
          DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.POSTGRES_DB }}
          
          # RabbitMQ
          RABBITMQ_URL=amqp://${{ secrets.RABBITMQ_USER }}:${{ secrets.RABBITMQ_PASSWORD }}@rabbitmq:5672/
          
          # Config
          ENVIRONMENT=production
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          EOF
          
          echo "âœ… App .env files generated from Forgejo Secrets"

      - name: ðŸ³ Prepare docker-compose.yml
        run: |
          # Copy template to compose directory
          mkdir -p /opt/superdeploy/compose
          cp /opt/superdeploy/compose/docker-compose.yml.template /opt/superdeploy/compose/docker-compose.yml
          
          echo "âœ… docker-compose.yml ready"

      - name: ðŸ³ Pull and deploy services
        run: |
          cd /opt/superdeploy/compose
          
          # Load infrastructure env (for DOCKER_ORG, etc.)
          set -a
          source /opt/superdeploy/.env
          set +a
          
          # Set image tags (use 'latest' if not specified)
          export API_IMAGE_TAG="${{ github.event.inputs.api_image_tag || 'latest' }}"
          export DASHBOARD_IMAGE_TAG="${{ github.event.inputs.dashboard_image_tag || 'latest' }}"
          export SERVICES_IMAGE_TAG="${{ github.event.inputs.services_image_tag || 'latest' }}"
          
          # Ensure DOCKER_REGISTRY is set
          export DOCKER_REGISTRY="${DOCKER_REGISTRY:-docker.io}"
          
          # Set DB/Queue credentials from Forgejo Secrets
          export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
          export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
          export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
          export RABBITMQ_USER="${{ secrets.RABBITMQ_USER }}"
          export RABBITMQ_PASSWORD="${{ secrets.RABBITMQ_PASSWORD }}"
          
          echo "Pulling images..."
          docker compose pull
          
          echo "Starting services..."
          docker compose up -d --remove-orphans
          
          echo "âœ… Services deployed!"

      - name: â³ Wait for services to be healthy
        run: |
          cd /opt/superdeploy/compose
          
          echo "Waiting for services to be healthy..."
          sleep 10
          
          docker compose ps
          echo "âœ… Services should be healthy!"

      - name: ðŸ“Š Show deployment status
        run: |
          cd /opt/superdeploy/compose
          
          echo "â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•"
          echo "         ðŸŽ‰ DEPLOYMENT COMPLETE! ðŸŽ‰                    "
          echo "â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•"
          echo ""
          docker compose ps
          echo ""
          echo "ðŸŒ Services are available at: http://$(curl -s ifconfig.me)"
