name: Deploy API

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image to deploy'
        required: true
      env_bundle:
        description: 'Encrypted environment bundle (base64)'
        required: true
      git_sha:
        description: 'Git commit SHA'
        required: true

jobs:
  deploy:
    runs-on: 
      - self-hosted
      - cheapa
      - app
    
    steps:
      - name: Display deployment info
        run: |
          echo "🚀 Deploying API..."
          echo "  Image: ${{ inputs.image }}"
          echo "  Git SHA: ${{ inputs.git_sha }}"
          echo ""
      
      - name: Decrypt environment bundle
        run: |
          echo "${{ inputs.env_bundle }}" | base64 -d | age -d -i /opt/forgejo-runner/.age/key.txt > /tmp/api.env
          echo "✓ Environment decrypted"
      
      - name: Pull latest image
        run: |
          cd /opt/superdeploy/projects/cheapa/compose
          docker compose pull api
          echo "✓ Image pulled"
      
      - name: Update container with new env
        run: |
          cd /opt/superdeploy/projects/cheapa/compose
          # Merge decrypted env with docker-compose
          docker compose --env-file /tmp/api.env up -d api
          echo "✓ Container restarted"
      
      - name: Cleanup
        if: always()
        run: |
          rm -f /tmp/api.env
          echo "✓ Cleanup complete"
      
      - name: Wait for health check
        run: |
          sleep 5
          if docker ps | grep -q cheapa-api; then
            echo "✓ API container is running"
          else
            echo "✗ API container not running"
            exit 1
          fi

