name: Deploy Service

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name (e.g., cheapa, myapp)'
        required: true
        type: string
      service:
        description: 'Service name (e.g., api, dashboard, services)'
        required: true
        type: string
      image:
        description: 'Docker image with tag (e.g., ghcr.io/cheapaio/api:abc123)'
        required: true
        type: string
      env_bundle:
        description: 'AGE-encrypted environment variables bundle'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA (for tracking)'
        required: true
        type: string
      git_ref:
        description: 'Git ref (branch/tag)'
        required: false
        default: 'production'
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, ${{ github.event.client_payload.project || inputs.project }}]
    
    env:
      PROJECT: ${{ github.event.client_payload.project || inputs.project }}
      SERVICE: ${{ github.event.client_payload.service || inputs.service }}
      IMAGE: ${{ github.event.client_payload.image || inputs.image }}
      ENV_BUNDLE: ${{ github.event.client_payload.env_bundle || inputs.env_bundle }}
      GIT_SHA: ${{ github.event.client_payload.git_sha || inputs.git_sha }}
      GIT_REF: ${{ github.event.client_payload.git_ref || inputs.git_ref }}
    
    steps:
      - name: Checkout superdeploy repo
        uses: actions/checkout@v4
      
      - name: Decrypt environment bundle
        id: decrypt
        run: |
          echo "${{ env.ENV_BUNDLE }}" | base64 -d > /tmp/encrypted.age
          age -d -i ~/.age/key.txt /tmp/encrypted.age > /tmp/decrypted.env
          rm /tmp/encrypted.age
          echo "env_file=/tmp/decrypted.env" >> $GITHUB_OUTPUT
      
      - name: Load environment variables
        run: |
          set -a
          source /tmp/decrypted.env
          set +a
          
          # Save to GitHub env for next steps
          cat /tmp/decrypted.env >> $GITHUB_ENV
      
      - name: Generate docker-compose for service
        run: |
          mkdir -p /opt/apps/${{ env.PROJECT }}/compose
          
          # Generate compose file from template
          cat > /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml <<EOF
          version: '3.8'
          
          networks:
            ${{ env.PROJECT }}-network:
              external: true
          
          services:
            ${{ env.PROJECT }}-${{ env.SERVICE }}:
              image: ${{ env.IMAGE }}
              container_name: ${{ env.PROJECT }}-${{ env.SERVICE }}
              restart: unless-stopped
              networks:
                - ${{ env.PROJECT }}-network
              environment:
                # All env vars from decrypted bundle
          $(cat /tmp/decrypted.env | sed 's/^/        /')
              labels:
                com.superdeploy.project: "${{ env.PROJECT }}"
                com.superdeploy.service: "${{ env.SERVICE }}"
                com.superdeploy.release: "v\$(date +%Y%m%d-%H%M%S)"
                com.superdeploy.git.sha: "${{ env.GIT_SHA }}"
                com.superdeploy.git.ref: "${{ env.GIT_REF }}"
                com.superdeploy.deployed.at: "\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 40s
          EOF
      
      - name: Deploy service
        run: |
          cd /opt/apps/${{ env.PROJECT }}/compose
          
          # Pull latest image
          docker pull ${{ env.IMAGE }}
          
          # Deploy with zero-downtime
          docker compose -f docker-compose-${{ env.SERVICE }}.yml up -d --wait
          
          # Wait for health check
          timeout 120 bash -c 'until docker inspect --format="{{.State.Health.Status}}" ${{ env.PROJECT }}-${{ env.SERVICE }} | grep -q "healthy"; do sleep 2; done' || {
            echo "❌ Health check failed!"
            docker logs ${{ env.PROJECT }}-${{ env.SERVICE }} --tail 50
            exit 1
          }
      
      - name: Cleanup old images
        run: |
          # Keep last 3 images
          docker images ghcr.io/*/${{ env.SERVICE }} --format "{{.ID}}" | tail -n +4 | xargs -r docker rmi || true
      
      - name: Clean up secrets
        if: always()
        run: |
          rm -f /tmp/decrypted.env
          rm -f /tmp/encrypted.age
      
      - name: Send notification
        if: always()
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" == "success" ]; then
            EMOJI="✅"
            COLOR="good"
          else
            EMOJI="❌"
            COLOR="danger"
          fi
          
          # Send email notification
          echo "Deployment $STATUS: ${{ env.PROJECT }}/${{ env.SERVICE }} @ ${{ env.GIT_SHA }}" | \
            mail -s "[$EMOJI] Deployment $STATUS" $ALERT_EMAIL || true
