name: 🌐 Deploy PROXY VM

on:
  push:
    branches:
      - master
    paths:
      - 'deploy/compose/vm3-proxy/**'
      - '.forgejo/workflows/deploy-proxy.yml'
  workflow_dispatch:

env:
  PROXY_HOST: 10.0.0.6
  PROXY_USER: superdeploy
  COMPOSE_DIR: /opt/superdeploy/compose

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: 📦 Checkout code
        run: |
          # Fix git safe directory
          git config --global --add safe.directory /opt/superdeploy
          
          # Initialize git if not exists
          if [ ! -d /opt/superdeploy/.git ]; then
            cd /opt/superdeploy
            git init
            git remote add origin http://34.56.43.99:3001/cradexco/superdeploy-app.git
            git config user.email "runner@superdeploy.local"
            git config user.name "Superdeploy Runner"
          fi
          
          # Fetch and checkout
          cd /opt/superdeploy
          git fetch origin ${{ github.ref_name }} || true
          git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
          git pull origin ${{ github.ref_name }} || true
          echo "✅ Code checked out: $(git rev-parse --short HEAD 2>/dev/null || echo 'initial')"

      - name: 🔐 Generate .env from Forgejo Secrets
        run: |
          cat > /tmp/proxy.env << EOF
          # Generated by Forgejo Actions on $(date)
          
          # Proxy Configuration
          PROXY_USER=${{ vars.PROXY_USER }}
          PROXY_PASSWORD=${{ secrets.PROXY_PASSWORD }}
          PROXY_EXTERNAL_IP=${{ vars.PROXY_EXTERNAL_IP }}
          SOCKS5_PORT=${{ vars.SOCKS5_PORT }}
          HTTP_PROXY_PORT=${{ vars.HTTP_PROXY_PORT }}
          
          # Proxy Registry Connection
          PROXY_REGISTRY_HOST=${{ vars.CORE_INTERNAL_IP }}
          PROXY_REGISTRY_PORT=${{ vars.PROXY_REGISTRY_PORT }}
          PROXY_REGISTRY_API_KEY=${{ secrets.PROXY_REGISTRY_API_KEY }}
          
          # IP Monitoring Configuration
          IP_CHECK_INTERVAL=${{ vars.IP_CHECK_INTERVAL }}
          IP_CHECK_URL=${{ vars.IP_CHECK_URL }}
          IP_UPDATE_ENDPOINT=${{ vars.IP_UPDATE_ENDPOINT }}
          
          # Access Control
          ALLOWED_IPS=${{ vars.PROXY_ALLOWED_IPS }}
          EOF
          
          echo "✅ .env file generated from secrets"

      - name: 📤 Copy files to PROXY VM
        run: |
          # Copy .env file
          scp -o StrictHostKeyChecking=no /tmp/proxy.env ${{ env.PROXY_USER }}@${{ env.PROXY_HOST }}:${{ env.COMPOSE_DIR }}/.env
          
          # Copy compose files
          scp -o StrictHostKeyChecking=no -r /opt/superdeploy/deploy/compose/vm3-proxy/* ${{ env.PROXY_USER }}@${{ env.PROXY_HOST }}:${{ env.COMPOSE_DIR }}/
          
          echo "✅ Files copied to PROXY VM"

      - name: 🐳 Deploy on PROXY VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.PROXY_USER }}@${{ env.PROXY_HOST }} << 'ENDSSH'
            cd ${{ env.COMPOSE_DIR }}
            
            # Pull latest images
            docker compose pull 2>&1 || echo "⚠️  No pre-built images, will build locally"
            
            # Deploy services
            docker compose up -d --build
            
            echo "✅ Services deployed on PROXY VM"
          ENDSSH

      - name: ⏳ Wait and test proxies
        run: |
          echo "⏳ Waiting 10s for services..."
          sleep 10
          
          echo ""
          echo "🧪 Testing HTTP Proxy..."
          curl -x http://${{ vars.PROXY_EXTERNAL_IP }}:${{ vars.HTTP_PROXY_PORT }} http://httpbin.org/ip || echo "⚠️  Proxy test failed"
          
          echo ""
          echo "🧪 Testing SOCKS5 Proxy..."
          curl --socks5 ${{ vars.PROXY_EXTERNAL_IP }}:${{ vars.SOCKS5_PORT }} http://httpbin.org/ip || echo "⚠️  Proxy test failed"

      - name: 📊 Check service status
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.PROXY_USER }}@${{ env.PROXY_HOST }} << 'ENDSSH'
            cd ${{ env.COMPOSE_DIR }}
            
            echo "=== Container Status ==="
            docker compose ps
            
            echo ""
            echo "=== Service Logs (last 15 lines) ==="
            docker compose logs --tail=15
          ENDSSH

      - name: 🧹 Cleanup
        run: |
          rm -f /tmp/proxy.env
          ssh -o StrictHostKeyChecking=no ${{ env.PROXY_USER }}@${{ env.PROXY_HOST }} \
            "docker image prune -f"
          echo "✅ Cleanup complete"

      - name: 🎉 Deployment Summary
        run: |
          echo "╔══════════════════════════════════════════════════════════════╗"
          echo "║  ✅ PROXY VM Deployment Successful                           ║"
          echo "╚══════════════════════════════════════════════════════════════╝"
          echo ""
          echo "🌐 Proxy Services:"
          echo "  • HTTP Proxy:  http://${{ vars.PROXY_EXTERNAL_IP }}:${{ vars.HTTP_PROXY_PORT }}"
          echo "  • SOCKS5:      socks5://${{ vars.PROXY_EXTERNAL_IP }}:${{ vars.SOCKS5_PORT }}"
          echo ""
          echo "📝 Commit: ${{ github.sha }}"
          echo "👤 Author: ${{ github.actor }}"
          echo "⏰ Time: $(date)"

