# =============================================================================
# SuperDeploy - Deployment Workflow for Project: cheapa
# =============================================================================
# Triggered by GitHub Actions via workflow_dispatch API
# Runs ONLY on cheapa project VMs
# =============================================================================

name: Deploy Application (cheapa)

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App name (e.g., api, storefront)'
        required: true
        type: string
      vm_role:
        description: 'VM role (e.g., app, core)'
        required: true
        type: string
      image:
        description: 'Docker image (e.g., c100394/api:latest)'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA'
        required: true
        type: string

jobs:
  deploy:
    # Project-specific runner labels - only cheapa VMs will pick this up
    runs-on: 
      - self-hosted
      - cheapa
      - app
    
    env:
      PROJECT: cheapa
      APP: ${{ inputs.app }}
      VM_ROLE: ${{ inputs.vm_role }}
      IMAGE: ${{ inputs.image }}
      GIT_SHA: ${{ inputs.git_sha }}
    
    steps:
      - name: Validate runner project
        run: |
          echo "๐ Validating runner project..."
          
          # Each VM has a .project file identifying which project it runs
          if [ ! -f /opt/superdeploy/.project ]; then
            echo "โ ERROR: /opt/superdeploy/.project not found!"
            echo "   This VM is not properly configured."
            exit 1
          fi
          
          RUNNER_PROJECT=$(cat /opt/superdeploy/.project)
          
          if [ "$RUNNER_PROJECT" != "$PROJECT" ]; then
            echo "โ ERROR: Wrong VM!"
            echo "   This runner is for project: $RUNNER_PROJECT"
            echo "   But job is for project: $PROJECT"
            exit 1
          fi
          
          echo "โ Correct VM for project: $RUNNER_PROJECT"
          echo ""
      
      - name: Check if app exists on this VM
        id: check_app
        run: |
          echo "๐ Checking if $APP is configured on this VM..."
          
          cd /opt/superdeploy/projects/$PROJECT/compose
          
          # Check if app is defined in docker-compose.yml
          if docker compose config 2>/dev/null | grep -q "^  $APP:"; then
            echo "โ App '$APP' is configured on this VM"
            echo "app_exists=true" >> $GITHUB_OUTPUT
          else
            echo "โญ๏ธ  Skipping: App '$APP' not configured on this VM"
            echo "app_exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Display deployment info
        if: steps.check_app.outputs.app_exists == 'true'
        run: |
          echo "๐ Deploying application..."
          echo "  Project: $PROJECT"
          echo "  App: $APP"
          echo "  VM Role: $VM_ROLE"
          echo "  Image: $IMAGE"
          echo "  Git SHA: $GIT_SHA"
          echo ""
      
      - name: Pull latest image
        if: steps.check_app.outputs.app_exists == 'true'
        run: |
          cd /opt/superdeploy/projects/$PROJECT/compose
          docker compose pull $APP
      
      - name: Restart container
        if: steps.check_app.outputs.app_exists == 'true'
        run: |
          cd /opt/superdeploy/projects/$PROJECT/compose
          docker compose up -d $APP
      
      - name: Wait for health check
        if: steps.check_app.outputs.app_exists == 'true'
        run: |
          echo "โณ Waiting for container to be healthy..."
          sleep 5
          
          # Check container status (docker-compose uses underscore in names)
          CONTAINER_NAME="${PROJECT}_${APP}"
          STATUS=$(docker inspect -f '{{.State.Status}}' $CONTAINER_NAME 2>/dev/null || echo "not_found")
          
          if [ "$STATUS" = "running" ]; then
            echo "โ Container is running!"
          else
            echo "โ Container failed to start (status: $STATUS)"
            docker logs $CONTAINER_NAME --tail 50
            exit 1
          fi
      
      - name: Cleanup old images
        if: steps.check_app.outputs.app_exists == 'true'
        run: |
          docker image prune -f
          echo "๐งน Cleanup complete"
      
      - name: Deployment summary
        if: steps.check_app.outputs.app_exists == 'true'
        run: |
          echo ""
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo "โ Deployment successful!"
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo "  Project: $PROJECT"
          echo "  App: $APP"
          echo "  Image: $IMAGE"
          echo "  SHA: $GIT_SHA"
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo ""
