name: Deploy CORE VM (Registry-Based)

on:
  workflow_dispatch:
    inputs:
      api_image_tag:
        description: 'API image tag (e.g., v1.2.3 or abc123) - leave empty to skip'
        required: false
        default: ''
      dashboard_image_tag:
        description: 'Dashboard image tag - leave empty to skip'
        required: false
        default: ''
      proxy_registry_image_tag:
        description: 'Proxy Registry image tag - leave empty to skip'
        required: false
        default: ''
  push:
    branches: [master]
    paths:
      - 'deploy/compose/vm1-core/.env.versions'
      - '.forgejo/workflows/deploy-core-v2.yml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: ๐ Deployment Info
        run: |
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo "โ           ๐ CORE VM Deployment (Registry-Based)          โ"
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo ""
          echo "๐ฆ Image Tags:"
          echo "  API:            ${API_TAG:-current}"
          echo "  Dashboard:      ${DASH_TAG:-current}"
          echo "  Proxy Registry: ${PROXY_TAG:-current}"
          echo ""
        env:
          API_TAG: ${{ inputs.api_image_tag }}
          DASH_TAG: ${{ inputs.dashboard_image_tag }}
          PROXY_TAG: ${{ inputs.proxy_registry_image_tag }}

      - name: ๐ฆ Checkout code
        run: |
          git config --global --add safe.directory /opt/superdeploy
          cd /opt/superdeploy
          git fetch origin master
          git reset --hard origin/master
          echo "โ Code updated"

      - name: ๐ Load .env configuration
        run: |
          cd /opt/superdeploy
          if [ ! -f .env ]; then
            echo "โ ERROR: .env file not found!"
            exit 1
          fi
          set -a
          source .env
          set +a
          echo "โ Environment loaded"
          echo "CORE_EXTERNAL_IP=${CORE_EXTERNAL_IP}" >> $GITHUB_ENV
          echo "CORE_INTERNAL_IP=${CORE_INTERNAL_IP}" >> $GITHUB_ENV

      - name: ๐ Update version file
        run: |
          cd /opt/superdeploy/deploy/compose/vm1-core
          
          # Update API version if provided
          if [ -n "${{ inputs.api_image_tag }}" ]; then
            echo "๐ Updating API version to ${{ inputs.api_image_tag }}"
            sed -i "s/^API_IMAGE_TAG=.*/API_IMAGE_TAG=${{ inputs.api_image_tag }}/" .env.versions
            echo "API_IMAGE_TAG=${{ inputs.api_image_tag }}" >> $GITHUB_ENV
          else
            # Load current version
            source .env.versions
            echo "API_IMAGE_TAG=${API_IMAGE_TAG}" >> $GITHUB_ENV
          fi
          
          # Update Dashboard version if provided
          if [ -n "${{ inputs.dashboard_image_tag }}" ]; then
            echo "๐ Updating Dashboard version to ${{ inputs.dashboard_image_tag }}"
            sed -i "s/^DASHBOARD_IMAGE_TAG=.*/DASHBOARD_IMAGE_TAG=${{ inputs.dashboard_image_tag }}/" .env.versions
            echo "DASHBOARD_IMAGE_TAG=${{ inputs.dashboard_image_tag }}" >> $GITHUB_ENV
          else
            source .env.versions
            echo "DASHBOARD_IMAGE_TAG=${DASHBOARD_IMAGE_TAG}" >> $GITHUB_ENV
          fi
          
          # Update Proxy Registry version if provided
          if [ -n "${{ inputs.proxy_registry_image_tag }}" ]; then
            echo "๐ Updating Proxy Registry version to ${{ inputs.proxy_registry_image_tag }}"
            sed -i "s/^PROXY_REGISTRY_IMAGE_TAG=.*/PROXY_REGISTRY_IMAGE_TAG=${{ inputs.proxy_registry_image_tag }}/" .env.versions
            echo "PROXY_REGISTRY_IMAGE_TAG=${{ inputs.proxy_registry_image_tag }}" >> $GITHUB_ENV
          else
            source .env.versions
            echo "PROXY_REGISTRY_IMAGE_TAG=${PROXY_REGISTRY_IMAGE_TAG}" >> $GITHUB_ENV
          fi
          
          # Update deployment metadata
          sed -i "s/^LAST_DEPLOY_DATE=.*/LAST_DEPLOY_DATE=$(date -Iseconds)/" .env.versions
          sed -i "s/^LAST_DEPLOY_BY=.*/LAST_DEPLOY_BY=workflow/" .env.versions
          sed -i "s/^LAST_DEPLOY_COMMIT=.*/LAST_DEPLOY_COMMIT=$(cd /opt/superdeploy && git rev-parse --short HEAD)/" .env.versions
          
          echo "โ Version file updated"
          cat .env.versions

      - name: ๐ Copy environment files
        run: |
          cd /opt/superdeploy
          
          # Copy main .env
          cp .env deploy/compose/vm1-core/.env
          
          # Append version overrides
          cat deploy/compose/vm1-core/.env.versions >> deploy/compose/vm1-core/.env
          
          echo "โ Environment files ready"

      - name: ๐ณ Pull new images
        run: |
          cd /opt/superdeploy/deploy/compose/vm1-core
          
          echo "๐ฅ Pulling images..."
          
          # Pull only services with updated tags
          if [ -n "${{ inputs.api_image_tag }}" ]; then
            echo "  API: cheapa/api:${{ inputs.api_image_tag }}"
            docker pull cheapa/api:${{ inputs.api_image_tag }} || echo "โ๏ธ  Image not found in registry, will build locally"
          fi
          
          if [ -n "${{ inputs.dashboard_image_tag }}" ]; then
            echo "  Dashboard: cheapa/dashboard:${{ inputs.dashboard_image_tag }}"
            docker pull cheapa/dashboard:${{ inputs.dashboard_image_tag }} || echo "โ๏ธ  Image not found in registry, will build locally"
          fi
          
          if [ -n "${{ inputs.proxy_registry_image_tag }}" ]; then
            echo "  Proxy Registry: cheapa/proxy-registry:${{ inputs.proxy_registry_image_tag }}"
            docker pull cheapa/proxy-registry:${{ inputs.proxy_registry_image_tag }} || echo "โ๏ธ  Image not found in registry, will build locally"
          fi
          
          echo "โ Images pulled"

      - name: ๐๏ธ  Build images if not in registry (fallback)
        run: |
          cd /opt/superdeploy/deploy/compose/vm1-core
          
          # Build local images if registry pull failed
          if [ -n "${{ inputs.api_image_tag }}" ] && ! docker image inspect cheapa/api:${{ inputs.api_image_tag }} >/dev/null 2>&1; then
            echo "๐๏ธ  Building API image locally..."
            docker build -t cheapa/api:${{ inputs.api_image_tag }} ./api
          fi
          
          if [ -n "${{ inputs.dashboard_image_tag }}" ] && ! docker image inspect cheapa/dashboard:${{ inputs.dashboard_image_tag }} >/dev/null 2>&1; then
            echo "๐๏ธ  Building Dashboard image locally..."
            docker build -t cheapa/dashboard:${{ inputs.dashboard_image_tag }} ./dashboard
          fi
          
          if [ -n "${{ inputs.proxy_registry_image_tag }}" ] && ! docker image inspect cheapa/proxy-registry:${{ inputs.proxy_registry_image_tag }} >/dev/null 2>&1; then
            echo "๐๏ธ  Building Proxy Registry image locally..."
            docker build -t cheapa/proxy-registry:${{ inputs.proxy_registry_image_tag }} ./proxy-registry
          fi
          
          echo "โ Images ready"

      - name: ๐ Deploy services
        run: |
          cd /opt/superdeploy/deploy/compose/vm1-core
          
          echo "๐ Deploying services..."
          docker compose up -d
          
          echo "โ Services deployed"

      - name: โณ Wait for services
        run: |
          echo "โณ Waiting for services to stabilize (30s)..."
          sleep 30

      - name: ๐ฅ Health checks
        run: |
          echo "๐ฅ Running health checks..."
          
          # Check API
          if curl -sf http://localhost:8000/health >/dev/null; then
            echo "  โ API healthy"
          else
            echo "  โ API unhealthy"
            exit 1
          fi
          
          # Check Proxy Registry
          if curl -sf http://localhost:8080/health >/dev/null; then
            echo "  โ Proxy Registry healthy"
          else
            echo "  โ๏ธ  Proxy Registry check failed (might be starting)"
          fi
          
          # Check Dashboard
          if curl -sf http://localhost:8001 >/dev/null; then
            echo "  โ Dashboard healthy"
          else
            echo "  โ๏ธ  Dashboard check failed"
          fi
          
          echo ""
          echo "โ Health checks completed"

      - name: ๐ Service status
        run: |
          cd /opt/superdeploy/deploy/compose/vm1-core
          echo "๐ Current service status:"
          docker compose ps

      - name: ๐งน Cleanup old images
        run: |
          echo "๐งน Cleaning up dangling images..."
          docker image prune -f
          echo "โ Cleanup complete"

      - name: ๐ Deployment summary
        run: |
          echo ""
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo "โ              ๐ DEPLOYMENT SUCCESSFUL! ๐                  โ"
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo ""
          echo "๐ Access Points:"
          echo "  API:            http://${{ env.CORE_EXTERNAL_IP }}:8000"
          echo "  Dashboard:      http://${{ env.CORE_EXTERNAL_IP }}:8001"
          echo "  Proxy Registry: http://${{ env.CORE_INTERNAL_IP }}:8080"
          echo ""
          echo "๐ฆ Deployed Versions:"
          echo "  API:            ${{ env.API_IMAGE_TAG }}"
          echo "  Dashboard:      ${{ env.DASHBOARD_IMAGE_TAG }}"
          echo "  Proxy Registry: ${{ env.PROXY_REGISTRY_IMAGE_TAG }}"
          echo ""
          echo "๐ Deployed at: $(date -Iseconds)"
          echo ""

