name: ๐ Deploy CORE VM

on:
  push:
    branches:
      - master
    paths:
      - 'deploy/compose/vm1-core/**'
      - '.forgejo/workflows/deploy-core.yml'
  workflow_dispatch:

env:
  COMPOSE_DIR: /opt/superdeploy/compose
  REPO_URL: http://${{ vars.CORE_EXTERNAL_IP }}:3001/cradexco/superdeploy-app.git
  WORKING_DIR: /opt/superdeploy

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: ๐ฆ Checkout code
        run: |
          # Initialize git if not exists
          if [ ! -d ${{ env.WORKING_DIR }}/.git ]; then
            cd ${{ env.WORKING_DIR }}
            git init
            git remote add origin ${{ env.REPO_URL }}
            git config user.email "runner@superdeploy.local"
            git config user.name "Superdeploy Runner"
          fi
          
          # Fetch and checkout
          cd ${{ env.WORKING_DIR }}
          git fetch origin ${{ github.ref_name }} || true
          git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
          git pull origin ${{ github.ref_name }} || true
          echo "โ Code checked out: $(git rev-parse --short HEAD 2>/dev/null || echo 'initial')"

      - name: ๐ Generate .env from Forgejo Secrets
        run: |
          cat > /tmp/core.env << EOF
          # Generated by Forgejo Actions on $(date)
          
          # Database Configuration
          POSTGRES_DB=superdeploy
          POSTGRES_USER=superdeploy
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST=postgres
          POSTGRES_PORT=5432
          
          # RabbitMQ Configuration
          RABBITMQ_DEFAULT_USER=superdeploy
          RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_PASSWORD }}
          RABBITMQ_DEFAULT_VHOST=/
          RABBITMQ_HOST=rabbitmq
          RABBITMQ_PORT=5672
          RABBITMQ_MANAGEMENT_PORT=15672
          
          # API Configuration
          API_HOST=0.0.0.0
          API_PORT=8000
          API_WORKERS=2
          API_LOG_LEVEL=info
          API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}
          API_DEBUG=false
          
          # Proxy Registry Configuration
          PROXY_REGISTRY_HOST=0.0.0.0
          PROXY_REGISTRY_PORT=8080
          PROXY_REGISTRY_API_KEY=${{ secrets.PROXY_REGISTRY_API_KEY }}
          
          # Dashboard Configuration
          DASHBOARD_HOST=0.0.0.0
          DASHBOARD_PORT=3000
          DASHBOARD_API_URL=http://api:8000
          DASHBOARD_PROXY_REGISTRY_URL=http://proxy_registry:8080
          
          # Caddy Configuration
          CADDY_DOMAIN=${{ vars.CADDY_DOMAIN }}
          CADDY_EMAIL=${{ vars.CADDY_EMAIL }}
          
          # Network Configuration
          CORE_EXTERNAL_IP=${{ vars.CORE_EXTERNAL_IP }}
          CORE_INTERNAL_IP=${{ vars.CORE_INTERNAL_IP }}
          SCRAPE_INTERNAL_IP=${{ vars.SCRAPE_INTERNAL_IP }}
          PROXY_INTERNAL_IP=${{ vars.PROXY_INTERNAL_IP }}
          
          # Monitoring
          LOG_LEVEL=${{ vars.LOG_LEVEL }}
          ENABLE_METRICS=${{ vars.ENABLE_METRICS }}
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          EOF
          
          echo "โ .env file generated from secrets"

      - name: ๐ Copy files to deployment directory
        run: |
          cp /tmp/core.env ${{ env.COMPOSE_DIR }}/.env
          cp -r ${{ env.WORKING_DIR }}/deploy/compose/vm1-core/* ${{ env.COMPOSE_DIR }}/
          echo "โ Files copied to ${{ env.COMPOSE_DIR }}"

      - name: ๐ณ Pull latest images
        run: |
          cd ${{ env.COMPOSE_DIR }}
          docker compose pull 2>&1 || echo "โ๏ธ  No pre-built images, will build locally"

      - name: ๐จ Build and deploy services
        run: |
          cd ${{ env.COMPOSE_DIR }}
          docker compose up -d --build
          echo "โ Services deployed"

      - name: โณ Wait for services to be healthy
        run: |
          echo "โณ Waiting 30s for services..."
          sleep 30
          
          # Check API health
          for i in {1..10}; do
            if curl -f http://localhost:8000/health 2>/dev/null; then
              echo "โ API is healthy"
              break
            fi
            echo "โณ Waiting for API... ($i/10)"
            sleep 5
          done
          
          # Check Proxy Registry health
          for i in {1..10}; do
            if curl -f http://localhost:8080/health 2>/dev/null; then
              echo "โ Proxy Registry is healthy"
              break
            fi
            echo "โณ Waiting for Proxy Registry... ($i/10)"
            sleep 5
          done

      - name: ๐ Show deployment status
        run: |
          cd ${{ env.COMPOSE_DIR }}
          echo "=== Container Status ==="
          docker compose ps
          echo ""
          echo "=== Recent Logs ==="
          docker compose logs --tail=20

      - name: ๐งน Cleanup old images
        run: |
          docker image prune -f
          echo "โ Cleanup complete"

      - name: ๐ Deployment Summary
        run: |
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo "โ  โ CORE VM Deployment Successful                            โ"
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo ""
          echo "๐ Service URLs:"
          echo "  โข Dashboard:      http://34.56.43.99/"
          echo "  โข API:            http://34.56.43.99:8000"
          echo "  โข API Health:     http://34.56.43.99:8000/health"
          echo "  โข Proxy Registry: http://34.56.43.99:8080"
          echo "  โข RabbitMQ UI:    http://34.56.43.99:15672"
          echo ""
          echo "๐ Commit: ${{ github.sha }}"
          echo "๐ค Author: ${{ github.actor }}"
          echo "โฐ Time: $(date)"

