# =============================================================================
# SuperDeploy - Central Deployment Workflow (Forgejo)
# =============================================================================
# Triggered by GitHub Actions via workflow_dispatch API
# Routes deployment to correct project VM runner
# =============================================================================

name: Deploy Application to VM

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name (e.g., cheapa)'
        required: true
        type: string
      app:
        description: 'App name (e.g., api, storefront)'
        required: true
        type: string
      vm_role:
        description: 'VM role (e.g., app, core)'
        required: true
        type: string
      image:
        description: 'Docker image (e.g., c100394/api:latest)'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA'
        required: true
        type: string

jobs:
  deploy:
    # Apps only deploy to app VMs (not core VMs)
    # Core VMs are for backing services only (postgres, rabbitmq, etc.)
    # NOTE: Forgejo 13.0.1 bug - inputs don't work in runs-on!
    # Must hardcode project label. Multi-project support requires Forgejo upgrade.
    runs-on: 
      - self-hosted
      - cheapa
      - app
    
    env:
      PROJECT: ${{ inputs.project }}
      APP: ${{ inputs.app }}
      VM_ROLE: ${{ inputs.vm_role }}
      IMAGE: ${{ inputs.image }}
      GIT_SHA: ${{ inputs.git_sha }}
    
    steps:
      - name: Display deployment info
        run: |
          echo "๐ Deploying application..."
          echo "  Project: $PROJECT"
          echo "  App: $APP"
          echo "  VM Role: $VM_ROLE"
          echo "  Image: $IMAGE"
          echo "  Git SHA: $GIT_SHA"
          echo ""
      
      - name: Pull latest image
        run: |
          cd /opt/superdeploy/projects/$PROJECT/compose
          docker compose pull $APP
      
      - name: Restart container
        run: |
          cd /opt/superdeploy/projects/$PROJECT/compose
          docker compose up -d $APP
      
      - name: Wait for health check
        run: |
          echo "โณ Waiting for container to be healthy..."
          sleep 5
          
          # Check container status (docker-compose uses underscore in names)
          CONTAINER_NAME="${PROJECT}_${APP}"
          STATUS=$(docker inspect -f '{{.State.Status}}' $CONTAINER_NAME 2>/dev/null || echo "not_found")
          
          if [ "$STATUS" = "running" ]; then
            echo "โ Container is running!"
          else
            echo "โ Container failed to start (status: $STATUS)"
            docker logs $CONTAINER_NAME --tail 50
            exit 1
          fi
      
      - name: Cleanup old images
        run: |
          docker image prune -f
          echo "๐งน Cleanup complete"
      
      - name: Deployment summary
        run: |
          echo ""
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo "โ Deployment successful!"
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo "  Project: $PROJECT"
          echo "  App: $APP"
          echo "  Image: $IMAGE"
          echo "  SHA: $GIT_SHA"
          echo "โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ"
          echo ""

