name: Deploy Service (Orchestrator)

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name (e.g., cheapa, myapp)'
        required: true
        type: string
      service:
        description: 'Service name (e.g., api, dashboard, services)'
        required: true
        type: string
      image:
        description: 'Docker image with tag (e.g., ghcr.io/cheapaio/api:abc123)'
        required: true
        type: string
      env_bundle:
        description: 'AGE-encrypted environment variables bundle'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA (for tracking)'
        required: true
        type: string
      git_ref:
        description: 'Git ref (branch/tag)'
        required: false
        default: 'production'
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, ${{ inputs.project }}]
    
    steps:
      - name: Checkout orchestrator repo
        uses: actions/checkout@v4
        with:
          repository: superdeploy/orchestrator
          ref: master
      
      - name: Decrypt environment bundle
        id: decrypt
        run: |
          echo "${{ inputs.env_bundle }}" | base64 -d > /tmp/encrypted.age
          age -d -i ~/.age/key.txt /tmp/encrypted.age > /tmp/decrypted.env
          rm /tmp/encrypted.age
          echo "env_file=/tmp/decrypted.env" >> $GITHUB_OUTPUT
      
      - name: Load environment variables
        run: |
          set -a
          source /tmp/decrypted.env
          set +a
          
          # Export for docker compose
          export PROJECT=${{ inputs.project }}
          export SERVICE=${{ inputs.service }}
          export IMAGE=${{ inputs.image }}
          export GIT_SHA=${{ inputs.git_sha }}
          export GIT_REF=${{ inputs.git_ref }}
          
          # Save to GitHub env for next steps
          cat /tmp/decrypted.env >> $GITHUB_ENV
          echo "PROJECT=${{ inputs.project }}" >> $GITHUB_ENV
          echo "SERVICE=${{ inputs.service }}" >> $GITHUB_ENV
          echo "IMAGE=${{ inputs.image }}" >> $GITHUB_ENV
          echo "GIT_SHA=${{ inputs.git_sha }}" >> $GITHUB_ENV
      
      - name: Generate docker-compose for service
        run: |
          mkdir -p /opt/apps/${{ inputs.project }}/compose
          
          # Generate compose file from template
          cat > /opt/apps/${{ inputs.project }}/compose/docker-compose-${{ inputs.service }}.yml <<EOF
          version: '3.8'
          
          networks:
            ${{ inputs.project }}-network:
              external: true
          
          services:
            ${{ inputs.project }}-${{ inputs.service }}:
              image: ${{ inputs.image }}
              container_name: ${{ inputs.project }}-${{ inputs.service }}
              restart: unless-stopped
              networks:
                - ${{ inputs.project }}-network
              environment:
                # All env vars from decrypted bundle
          $(cat /tmp/decrypted.env | sed 's/^/        /')
              labels:
                com.superdeploy.project: "${{ inputs.project }}"
                com.superdeploy.service: "${{ inputs.service }}"
                com.superdeploy.release: "v\$(date +%Y%m%d-%H%M%S)"
                com.superdeploy.git.sha: "${{ inputs.git_sha }}"
                com.superdeploy.git.ref: "${{ inputs.git_ref }}"
                com.superdeploy.deployed.at: "\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 40s
          EOF
      
      - name: Deploy service
        run: |
          cd /opt/apps/${{ inputs.project }}/compose
          
          # Pull latest image
          docker pull ${{ inputs.image }}
          
          # Deploy with zero-downtime
          docker compose -f docker-compose-${{ inputs.service }}.yml up -d --wait
          
          # Wait for health check
          timeout 120 bash -c 'until docker inspect --format="{{.State.Health.Status}}" ${{ inputs.project }}-${{ inputs.service }} | grep -q "healthy"; do sleep 2; done' || {
            echo "❌ Health check failed!"
            docker logs ${{ inputs.project }}-${{ inputs.service }} --tail 50
            exit 1
          }
      
      - name: Cleanup old images
        run: |
          # Keep last 3 images
          docker images ghcr.io/${{ github.repository_owner }}/${{ inputs.service }} --format "{{.ID}}" | tail -n +4 | xargs -r docker rmi || true
      
      - name: Clean up secrets
        if: always()
        run: |
          rm -f /tmp/decrypted.env
          rm -f /tmp/encrypted.age
      
      - name: Send notification
        if: always()
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" == "success" ]; then
            EMOJI="✅"
            COLOR="good"
          else
            EMOJI="❌"
            COLOR="danger"
          fi
          
          # Send email notification
          echo "Deployment $STATUS: ${{ inputs.project }}/${{ inputs.service }} @ ${{ inputs.git_sha }}" | \
            mail -s "[$EMOJI] Deployment $STATUS" $ALERT_EMAIL || true
