name: Deploy Service

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name (e.g., cheapa, myapp)'
        required: true
        type: string
      service:
        description: 'Service name (e.g., api, dashboard, services)'
        required: true
        type: string
      image:
        description: 'Docker image with tag (e.g., ghcr.io/cheapaio/api:abc123)'
        required: true
        type: string
      env_bundle:
        description: 'AGE-encrypted environment variables bundle'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA (for tracking)'
        required: true
        type: string
      git_ref:
        description: 'Git ref (branch/tag)'
        required: false
        default: 'production'
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    
    env:
      PROJECT: ${{ inputs.project }}
      SERVICE: ${{ inputs.service }}
      IMAGE: ${{ inputs.image }}
      ENV_BUNDLE: ${{ inputs.env_bundle }}
      GIT_SHA: ${{ inputs.git_sha }}
      GIT_REF: ${{ inputs.git_ref }}
    
    steps:
      - name: Checkout superdeploy repo
        uses: actions/checkout@v4
      
      - name: Decrypt environment bundle
        id: decrypt
        run: |
          echo "${{ env.ENV_BUNDLE }}" | base64 -d > /tmp/encrypted.age
          age -d -i /opt/forgejo-runner/.age/key.txt /tmp/encrypted.age > /tmp/decrypted.env
          rm /tmp/encrypted.age
          echo "env_file=/tmp/decrypted.env" >> $GITHUB_OUTPUT
      
      - name: Load environment variables
        run: |
          set -a
          source /tmp/decrypted.env
          set +a
          
          # Save to GitHub env for next steps
          cat /tmp/decrypted.env >> $GITHUB_ENV
      
      - name: Login to Docker Hub
        run: |
          # Login using Docker Hub credentials from Forgejo secrets
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Generate docker-compose for service
        run: |
          mkdir -p /opt/apps/${{ env.PROJECT }}/compose
          
          # Generate compose file from template
          cat > /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml <<'EOF'
          version: '3.8'
          
          networks:
            PROJECT_NETWORK:
              external: true
          
          services:
            SERVICE_NAME:
              image: IMAGE_PLACEHOLDER
              container_name: CONTAINER_NAME
              restart: unless-stopped
              networks:
                - PROJECT_NETWORK
              env_file:
                - /tmp/decrypted.env
              labels:
                com.superdeploy.project: "PROJECT_PLACEHOLDER"
                com.superdeploy.service: "SERVICE_PLACEHOLDER"
                com.superdeploy.git.sha: "GIT_SHA_PLACEHOLDER"
                com.superdeploy.git.ref: "GIT_REF_PLACEHOLDER"
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 40s
          EOF
          
          # Replace placeholders
          sed -i "s|PROJECT_NETWORK|${{ env.PROJECT }}-network|g" /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml
          sed -i "s|SERVICE_NAME|${{ env.PROJECT }}-${{ env.SERVICE }}|g" /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml
          sed -i "s|CONTAINER_NAME|${{ env.PROJECT }}-${{ env.SERVICE }}|g" /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml
          sed -i "s|IMAGE_PLACEHOLDER|${{ env.IMAGE }}|g" /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml
          sed -i "s|PROJECT_PLACEHOLDER|${{ env.PROJECT }}|g" /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml
          sed -i "s|SERVICE_PLACEHOLDER|${{ env.SERVICE }}|g" /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml
          sed -i "s|GIT_SHA_PLACEHOLDER|${{ env.GIT_SHA }}|g" /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml
          sed -i "s|GIT_REF_PLACEHOLDER|${{ env.GIT_REF }}|g" /opt/apps/${{ env.PROJECT }}/compose/docker-compose-${{ env.SERVICE }}.yml
      
      - name: Deploy service
        run: |
          cd /opt/apps/${{ env.PROJECT }}/compose
          
          # Create project network if it doesn't exist
          docker network create ${{ env.PROJECT }}-network 2>/dev/null || true
          
          # Pull latest image
          docker pull ${{ env.IMAGE }}
          
          # Deploy with zero-downtime
          docker compose -f docker-compose-${{ env.SERVICE }}.yml up -d --wait
          
          # Wait for health check
          timeout 120 bash -c 'until docker inspect --format="{{.State.Health.Status}}" ${{ env.PROJECT }}-${{ env.SERVICE }} | grep -q "healthy"; do sleep 2; done' || {
            echo "❌ Health check failed!"
            docker logs ${{ env.PROJECT }}-${{ env.SERVICE }} --tail 50
            exit 1
          }
      
      - name: Cleanup old images
        run: |
          # Keep last 3 images
          docker images ghcr.io/*/${{ env.SERVICE }} --format "{{.ID}}" | tail -n +4 | xargs -r docker rmi || true
      
      - name: Clean up secrets
        if: always()
        run: |
          rm -f /tmp/decrypted.env
          rm -f /tmp/encrypted.age
      
      - name: Send notification
        if: always()
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" == "success" ]; then
            EMOJI="✅"
            COLOR="good"
          else
            EMOJI="❌"
            COLOR="danger"
          fi
          
          # Send email notification
          echo "Deployment $STATUS: ${{ env.PROJECT }}/${{ env.SERVICE }} @ ${{ env.GIT_SHA }}" | \
            mail -s "[$EMOJI] Deployment $STATUS" $ALERT_EMAIL || true
