name: 🔍 Deploy SCRAPE VM

on:
  push:
    branches:
      - master
    paths:
      - 'deploy/compose/vm2-scrape/**'
  workflow_dispatch:

env:
  SCRAPE_HOST: ${{ vars.SCRAPE_INTERNAL_IP }}
  SCRAPE_USER: superdeploy
  COMPOSE_DIR: /opt/superdeploy/compose
  REPO_URL: http://${{ vars.CORE_EXTERNAL_IP }}:3001/cradexco/superdeploy-app.git
  WORKING_DIR: /opt/superdeploy

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: 📦 Checkout code
        run: |
          cd ${{ env.WORKING_DIR }}
          git config --global init.defaultBranch master
          if [ ! -d .git ]; then
            git init -b master
            git remote add origin ${{ env.REPO_URL }}
            git config user.email "runner@superdeploy.local"
            git config user.name "Superdeploy Runner"
          fi
          git fetch origin master || true
          git checkout master || git checkout -b master
          git reset --hard origin/master || true
          git pull origin master || true
          echo "✅ Code checked out: $(git rev-parse --short HEAD 2>/dev/null || echo 'initial')"

      - name: 🔐 Prepare .env file
        run: |
          if [ ! -f ${{ env.WORKING_DIR }}/.env ]; then
            echo "❌ ERROR: .env file not found in repository!"
            exit 1
          fi
          cp ${{ env.WORKING_DIR }}/.env /tmp/scrape.env
          echo "✅ .env file loaded"

      - name: 📤 Copy files to SCRAPE VM
        run: |
          # Copy .env file
          scp -o StrictHostKeyChecking=no /tmp/scrape.env ${{ env.SCRAPE_USER }}@${{ env.SCRAPE_HOST }}:${{ env.COMPOSE_DIR }}/.env
          
          # Copy compose files
          scp -o StrictHostKeyChecking=no -r ${{ env.WORKING_DIR }}/deploy/compose/vm2-scrape/* ${{ env.SCRAPE_USER }}@${{ env.SCRAPE_HOST }}:${{ env.COMPOSE_DIR }}/
          
          echo "✅ Files copied to SCRAPE VM"

      - name: 🐳 Deploy on SCRAPE VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SCRAPE_USER }}@${{ env.SCRAPE_HOST }} << 'ENDSSH'
            cd ${{ env.COMPOSE_DIR }}
            
            # Pull latest images
            docker compose pull 2>&1 || echo "⚠️  No pre-built images, will build locally"
            
            # Deploy services
            docker compose up -d --build
            
            echo "✅ Services deployed on SCRAPE VM"
          ENDSSH

      - name: ⏳ Wait and check health
        run: |
          echo "⏳ Waiting 10s for services..."
          sleep 10

      - name: 📊 Check service status
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SCRAPE_USER }}@${{ env.SCRAPE_HOST }} << 'ENDSSH'
            cd ${{ env.COMPOSE_DIR }}
            
            echo "=== Container Status ==="
            docker compose ps
            
            echo ""
            echo "=== Worker Logs (last 20 lines) ==="
            docker compose logs --tail=20 worker || true
          ENDSSH

      - name: 🧹 Cleanup
        run: |
          rm -f /tmp/scrape.env
          ssh -o StrictHostKeyChecking=no ${{ env.SCRAPE_USER }}@${{ env.SCRAPE_HOST }} \
            "docker image prune -f"
          echo "✅ Cleanup complete"

      - name: 🎉 Deployment Summary
        run: |
          echo "╔══════════════════════════════════════════════════════════════╗"
          echo "║  ✅ SCRAPE VM Deployment Successful                          ║"
          echo "╚══════════════════════════════════════════════════════════════╝"
          echo ""
          echo "🔍 SCRAPE VM: ${{ env.SCRAPE_HOST }}"
          echo "📝 Commit: ${{ github.sha }}"
          echo "👤 Author: ${{ github.actor }}"
          echo "⏰ Time: $(date)"

# Updated Mon Oct 20 12:32:04 +03 2025
