name: Deploy Service

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name (e.g., cheapa, myapp)'
        required: true
        type: string
      service:
        description: 'Service name (e.g., api, dashboard, services)'
        required: true
        type: string
      image:
        description: 'Docker image with tag (e.g., ghcr.io/cheapaio/api:abc123)'
        required: true
        type: string
      env_bundle:
        description: 'AGE-encrypted environment variables bundle'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA (for tracking)'
        required: true
        type: string
      git_ref:
        description: 'Git ref (branch/tag)'
        required: false
        default: 'production'
        type: string

jobs:
  # Route to correct VM based on service type
  # Forgejo doesn't support expressions in runs-on, so we use conditional jobs with static labels
  
  deploy-api:
    if: ${{ inputs.service == 'api' }}
    runs-on: [self-hosted, api]
    steps:
      - name: Checkout superdeploy repo
        uses: actions/checkout@v4
      
      - uses: ./.forgejo/actions/deploy
        with:
          project: ${{ inputs.project }}
          service: ${{ inputs.service }}
          image: ${{ inputs.image }}
          env_bundle: ${{ inputs.env_bundle }}
          git_sha: ${{ inputs.git_sha }}
          git_ref: ${{ inputs.git_ref }}
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  
  deploy-web:
    if: ${{ inputs.service == 'dashboard' }}
    runs-on: [self-hosted, web]
    steps:
      - name: Checkout superdeploy repo
        uses: actions/checkout@v4
      
      - uses: ./.forgejo/actions/deploy
        with:
          project: ${{ inputs.project }}
          service: ${{ inputs.service }}
          image: ${{ inputs.image }}
          env_bundle: ${{ inputs.env_bundle }}
          git_sha: ${{ inputs.git_sha }}
          git_ref: ${{ inputs.git_ref }}
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  
  deploy-worker:
    if: ${{ inputs.service == 'services' }}
    runs-on: [self-hosted, worker]
    steps:
      - name: Checkout superdeploy repo
        uses: actions/checkout@v4
      
      - uses: ./.forgejo/actions/deploy
        with:
          project: ${{ inputs.project }}
          service: ${{ inputs.service }}
          image: ${{ inputs.image }}
          env_bundle: ${{ inputs.env_bundle }}
          git_sha: ${{ inputs.git_sha }}
          git_ref: ${{ inputs.git_ref }}
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
