name: Deploy Service (Reusable)

on:
  workflow_call:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: string
      service:
        description: 'Service name'
        required: true
        type: string
      port:
        description: 'Service port'
        required: true
        type: string
      image:
        description: 'Docker image with tag'
        required: true
        type: string
      env_bundle:
        description: 'AGE-encrypted environment bundle (base64)'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA'
        required: true
        type: string
      git_ref:
        description: 'Git ref (branch/tag)'
        required: false
        type: string
        default: 'production'
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      AGE_SECRET_KEY:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, ${{ inputs.project }}, app]
    
    steps:
      - name: Check age installation
        run: |
          if command -v age &> /dev/null; then
            echo "✅ age already installed ($(age --version))"
          else
            echo "📥 Installing age..."
            curl -sL https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz | tar xz
            sudo mv age/age /usr/local/bin/
            rm -rf age
            echo "✅ age installed ($(age --version))"
          fi
      
      - name: Decode env bundle
        run: |
          echo "📦 Decoding environment bundle..."
          echo "${{ inputs.env_bundle }}" | base64 -d > /tmp/encrypted.age
          SIZE=$(wc -c < /tmp/encrypted.age)
          echo "✅ Decoded: $SIZE bytes"
      
      - name: Decrypt with AGE
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
        run: |
          echo "🔐 Decrypting with AGE..."
          
          if [ -z "$AGE_SECRET_KEY" ]; then
            echo "❌ AGE_SECRET_KEY not set!"
            exit 1
          fi
          
          printf '%s' "$AGE_SECRET_KEY" > /tmp/age-key.txt
          chmod 600 /tmp/age-key.txt
          
          if ! age -d -i /tmp/age-key.txt /tmp/encrypted.age > /tmp/decrypted.env 2>&1; then
            echo "❌ Decryption failed!"
            cat /tmp/decrypted.env || true
            rm -f /tmp/age-key.txt /tmp/encrypted.age /tmp/decrypted.env
            exit 1
          fi
          
          rm -f /tmp/age-key.txt /tmp/encrypted.age
          
          if [ ! -s /tmp/decrypted.env ]; then
            echo "❌ Decrypted file is empty!"
            exit 1
          fi
          
          SIZE=$(wc -c < /tmp/decrypted.env)
          echo "✅ Decrypted: $SIZE bytes"
      
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "🔑 Logging in to Docker Hub..."
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
          echo "✅ Logged in"
      
      - name: Pull Docker image
        run: |
          echo "📥 Pulling: ${{ inputs.image }}"
          docker pull ${{ inputs.image }}
          echo "✅ Image pulled"
      
      - name: Generate Docker Compose file
        run: |
          echo "📝 Generating docker-compose.yml..."
          
          PROJECT="${{ inputs.project }}"
          SERVICE="${{ inputs.service }}"
          IMAGE="${{ inputs.image }}"
          PORT="${{ inputs.port }}"
          GIT_SHA="${{ inputs.git_sha }}"
          
          sudo mkdir -p /opt/apps/$PROJECT/compose
          
          cat > /tmp/docker-compose-$SERVICE.yml << EOF
          version: '3.8'
          services:
            $SERVICE:
              image: $IMAGE
              container_name: $PROJECT-$SERVICE
              restart: unless-stopped
              env_file:
                - /tmp/decrypted.env
              networks:
                - $PROJECT-network
              ports:
                - "$PORT:$PORT"
              labels:
                - "project=$PROJECT"
                - "service=$SERVICE"
                - "git.sha=$GIT_SHA"
          
          networks:
            $PROJECT-network:
              name: $PROJECT-network
              external: true
          EOF
          
          sudo mv /tmp/docker-compose-$SERVICE.yml /opt/apps/$PROJECT/compose/
          echo "✅ Compose file created"
      
      - name: Deploy container
        run: |
          echo "🚀 Deploying ${{ inputs.service }}..."
          
          cd /opt/apps/${{ inputs.project }}/compose
          docker compose -f docker-compose-${{ inputs.service }}.yml up -d
          
          echo "✅ Deployed successfully!"
      
      - name: Show container status
        run: |
          echo "📊 Container status:"
          docker ps --filter "name=${{ inputs.project }}-${{ inputs.service }}" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      
      - name: Cleanup
        if: always()
        run: |
          rm -f /tmp/decrypted.env /tmp/encrypted.age /tmp/age-key.txt
          echo "🧹 Cleanup complete"

