# =============================================================================
# SERVICE CI/CD WORKFLOW TEMPLATE
# =============================================================================
# Copy this to your service repository: .forgejo/workflows/ci.yml
# Update: SERVICE_NAME, DEPLOY_WORKFLOW, IMAGE_TAG_INPUT

name: Build & Deploy {{ SERVICE_NAME }}

on:
  push:
    branches: [main, master]
  create:
    tags: ['v*']

env:
  REGISTRY: docker.io  # or ghcr.io, registry.cheapa.io, etc.
  ORG: cheapa
  SERVICE_NAME: api  # CHANGE THIS: api, dashboard, worker, etc.
  DEPLOY_WORKFLOW: deploy-core-v2.yml  # CHANGE THIS: which workflow to trigger
  IMAGE_TAG_INPUT: api_image_tag  # CHANGE THIS: workflow input name

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # ========================================================================
      # 1. CHECKOUT CODE
      # ========================================================================
      - name: 📦 Checkout code
        run: |
          rm -rf /tmp/build-${{ github.run_id }}
          mkdir -p /tmp/build-${{ github.run_id }}
          cd /tmp/build-${{ github.run_id }}
          git clone ${{ github.repository_url }} .
          git config --global --add safe.directory /tmp/build-${{ github.run_id }}
          echo "✅ Code checked out"

      # ========================================================================
      # 2. GENERATE IMAGE TAG
      # ========================================================================
      - name: 🏷️  Generate image tag
        id: tag
        run: |
          cd /tmp/build-${{ github.run_id }}
          
          # If push is a version tag, use it
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            TAG="${{ github.ref_name }}"
            echo "📌 Version tag detected: $TAG"
          else
            # Otherwise use short commit SHA
            TAG=$(git rev-parse --short HEAD)
            echo "📌 Commit SHA tag: $TAG"
          fi
          
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          
          echo "✅ Tag: $TAG"

      # ========================================================================
      # 3. BUILD DOCKER IMAGE
      # ========================================================================
      - name: 🏗️  Build Docker image
        run: |
          cd /tmp/build-${{ github.run_id }}
          
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.SERVICE_NAME }}"
          
          echo "🏗️  Building image: ${IMAGE_NAME}:${{ env.IMAGE_TAG }}"
          
          docker build \
            -t ${IMAGE_NAME}:${{ env.IMAGE_TAG }} \
            -t ${IMAGE_NAME}:latest \
            --build-arg BUILD_DATE=$(date -Iseconds) \
            --build-arg VCS_REF=$(git rev-parse --short HEAD) \
            --build-arg VERSION=${{ env.IMAGE_TAG }} \
            .
          
          echo "✅ Image built successfully"

      # ========================================================================
      # 4. RUN TESTS (Optional)
      # ========================================================================
      - name: 🧪 Run tests
        run: |
          cd /tmp/build-${{ github.run_id }}
          
          # Uncomment and customize based on your service
          # docker run --rm ${IMAGE_NAME}:${{ env.IMAGE_TAG }} pytest
          # docker run --rm ${IMAGE_NAME}:${{ env.IMAGE_TAG }} npm test
          
          echo "✅ Tests passed (or skipped)"

      # ========================================================================
      # 5. PUSH TO REGISTRY
      # ========================================================================
      - name: 📤 Push to registry
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.SERVICE_NAME }}"
          
          # Login to registry (if credentials are provided)
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "✅ Logged in to registry"
          else
            echo "⚠️  No registry credentials - skipping push (will use local image)"
            exit 0
          fi
          
          echo "📤 Pushing images..."
          docker push ${IMAGE_NAME}:${{ env.IMAGE_TAG }}
          docker push ${IMAGE_NAME}:latest
          
          echo "✅ Images pushed to registry"

      # ========================================================================
      # 6. TRIGGER DEPLOYMENT
      # ========================================================================
      - name: 🚀 Trigger deployment in superdeploy-app
        run: |
          # Forgejo API endpoint for workflow dispatch
          API_URL="http://${{ env.FORGEJO_HOST }}:3001/api/v1/repos/${{ env.FORGEJO_OWNER }}/superdeploy-app/actions/workflows/${{ env.DEPLOY_WORKFLOW }}/dispatches"
          
          echo "🚀 Triggering deployment workflow..."
          echo "  Workflow: ${{ env.DEPLOY_WORKFLOW }}"
          echo "  Input: ${{ env.IMAGE_TAG_INPUT }}=${{ env.IMAGE_TAG }}"
          
          # Build JSON payload
          PAYLOAD=$(cat <<EOF
          {
            "ref": "master",
            "inputs": {
              "${{ env.IMAGE_TAG_INPUT }}": "${{ env.IMAGE_TAG }}"
            }
          }
          EOF
          )
          
          # Trigger workflow
          HTTP_CODE=$(curl -X POST \
            -H "Authorization: Bearer ${{ secrets.FORGEJO_PAT }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            -w "%{http_code}" \
            -o /tmp/deploy-response.json \
            "$API_URL")
          
          if [ "$HTTP_CODE" -eq 204 ] || [ "$HTTP_CODE" -eq 200 ]; then
            echo "✅ Deployment triggered successfully!"
          else
            echo "❌ Failed to trigger deployment (HTTP $HTTP_CODE)"
            cat /tmp/deploy-response.json
            exit 1
          fi
        env:
          FORGEJO_HOST: ${{ secrets.FORGEJO_HOST || '34.56.43.99' }}
          FORGEJO_OWNER: cradexco

      # ========================================================================
      # 7. CLEANUP
      # ========================================================================
      - name: 🧹 Cleanup
        if: always()
        run: |
          # Remove build directory
          rm -rf /tmp/build-${{ github.run_id }}
          
          # Cleanup old images (keep last 3)
          docker image prune -f
          
          echo "✅ Cleanup complete"

      # ========================================================================
      # 8. SUMMARY
      # ========================================================================
      - name: 📋 Build summary
        run: |
          echo ""
          echo "╔════════════════════════════════════════════════════════════╗"
          echo "║              🎉 BUILD & DEPLOY COMPLETE! 🎉                ║"
          echo "╚════════════════════════════════════════════════════════════╝"
          echo ""
          echo "📦 Service:     ${{ env.SERVICE_NAME }}"
          echo "🏷️  Tag:        ${{ env.IMAGE_TAG }}"
          echo "🐳 Image:       ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }}"
          echo "🚀 Deployment:  Triggered"
          echo ""
          echo "📊 Monitor deployment:"
          echo "  http://${{ secrets.FORGEJO_HOST || '34.56.43.99' }}:3001/cradexco/superdeploy-app/actions"
          echo ""

