"""
Project initialization - interactive wizard with secrets management
"""

import yaml
import click
import secrets
from datetime import datetime
from rich.prompt import Prompt
from cli.base import BaseCommand


class InitCommand(BaseCommand):
    """Initialize new project with secrets.yml."""

    def __init__(self, project_name: str, verbose: bool = False):
        super().__init__(verbose=verbose)
        self.project_name = project_name

    def execute(self) -> None:
        """Execute init command."""
        self.show_header(
            title="Initialize Project",
            project=self.project_name,
            subtitle="Infrastructure + secrets setup",
        )

        from cli.utils import get_project_root

        project_root = get_project_root()
        project_dir = project_root / "projects" / self.project_name

        # Check if project exists
        if project_dir.exists():
            self.console.print(
                f"[yellow]Project exists: {self.project_name}. Overwrite? [y/n][/yellow] [dim](n)[/dim]: ",
                end="",
            )
            answer = input().strip().lower()
            if answer not in ["y", "yes"]:
                self.console.print("[dim]Cancelled[/dim]")
                return

        project_dir.mkdir(parents=True, exist_ok=True)

        # Cloud Provider
        self.console.print("\n[white]Cloud Provider[/white]")
        gcp_project = Prompt.ask("GCP Project ID", default="my-gcp-project")
        gcp_region = Prompt.ask("GCP Region", default="us-central1")

        # GitHub
        self.console.print("\n[white]GitHub[/white]")
        github_org = Prompt.ask("GitHub Organization", default=f"{self.project_name}io")

        # Apps
        self.console.print("\n[white]Applications[/white]")
        self.console.print("[dim]Enter app names (comma-separated)[/dim]")
        apps_input = Prompt.ask("Apps")
        app_names = [a.strip() for a in apps_input.split(",")]

        # App paths
        apps = {}
        for app_name in app_names:
            default_path = f"/path/to/{app_name}"
            app_path = Prompt.ask(f"  Path for {app_name}", default=default_path)
            default_port = "8000"
            app_port = Prompt.ask(f"  Port for {app_name}", default=default_port)

            apps[app_name] = {
                "path": app_path,
                "vm": "app",
                "port": int(app_port),
            }

        # Generate config.yml
        project_config = {
            "project": {
                "name": self.project_name,
                "description": f"{self.project_name} project",
                "created_at": datetime.now().isoformat(),
                "ssl_email": f"admin@{self.project_name}.io",
            },
            "cloud": {
                "gcp": {
                    "project_id": gcp_project,
                    "region": gcp_region,
                    "zone": f"{gcp_region}-a",
                },
                "ssh": {
                    "key_path": "~/.ssh/superdeploy_deploy",
                    "public_key_path": "~/.ssh/superdeploy_deploy.pub",
                    "user": "superdeploy",
                },
            },
            "vms": {
                "core": {
                    "count": 1,
                    "machine_type": "e2-medium",
                    "disk_size": 20,
                    "services": ["rabbitmq", "postgres"],
                },
                "app": {
                    "count": 1,
                    "machine_type": "e2-medium",
                    "disk_size": 30,
                    "services": [],
                },
            },
            "addons": {
                "rabbitmq": {"version": "3.12-management-alpine"},
                "postgres": {"version": "15-alpine"},
                "caddy": {"version": "2-alpine"},
            },
            "apps": apps,
            "docker": {
                "registry": "docker.io",
                "organization": "your-docker-org",  # User needs to edit
            },
            "github": {"organization": github_org},
            "network": {
                "vpc_subnet": "10.1.0.0/16",
                "docker_subnet": "172.30.0.0/24",
            },
        }

        # Generate config.yml with proper formatting
        project_yml = project_dir / "config.yml"

        # Build formatted YAML with comments
        yml_lines = []
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(f"# {self.project_name} - Project Configuration")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(f"# Auto-generated by: superdeploy {self.project_name}:init")
        yml_lines.append(
            f"# Edit this file, then run: superdeploy {self.project_name}:generate"
        )
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("")
        yml_lines.append("# Project Information")
        yml_lines.append(
            yaml.dump(
                {"project": project_config["project"]},
                default_flow_style=False,
                sort_keys=False,
            ).strip()
        )
        yml_lines.append("")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# Cloud Provider Configuration")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(
            yaml.dump(
                {"cloud": project_config["cloud"]},
                default_flow_style=False,
                sort_keys=False,
            ).strip()
        )
        yml_lines.append("")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# VMs (Infrastructure)")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(
            yaml.dump(
                {"vms": project_config["vms"]},
                default_flow_style=False,
                sort_keys=False,
            ).strip()
        )
        yml_lines.append("")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# Addons Configuration")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(
            yaml.dump(
                {"addons": project_config["addons"]},
                default_flow_style=False,
                sort_keys=False,
            ).strip()
        )
        yml_lines.append("")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# Application Services")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(
            yaml.dump(
                {"apps": project_config["apps"]},
                default_flow_style=False,
                sort_keys=False,
            ).strip()
        )
        yml_lines.append("")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# Docker Configuration")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(
            yaml.dump(
                {"docker": project_config["docker"]},
                default_flow_style=False,
                sort_keys=False,
            ).strip()
        )
        yml_lines.append("")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# GitHub Configuration")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(
            yaml.dump(
                {"github": project_config["github"]},
                default_flow_style=False,
                sort_keys=False,
            ).strip()
        )
        yml_lines.append("")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# Network Configuration")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(
            yaml.dump(
                {"network": project_config["network"]},
                default_flow_style=False,
                sort_keys=False,
            ).strip()
        )
        yml_lines.append("")

        with open(project_yml, "w") as f:
            f.write("\n".join(yml_lines))

        self.console.print(
            f"\n[dim]✓ Created: {project_yml.relative_to(project_root)}[/dim]"
        )

        # Generate secrets.yml with template
        self.console.print("\n[dim]Generating secrets...[/dim]")

        postgres_password = secrets.token_urlsafe(32)
        rabbitmq_password = secrets.token_urlsafe(32)

        passwords_config = {
            "secrets": {
                "shared": {
                    "POSTGRES_HOST": "postgres",
                    "POSTGRES_PORT": "5432",
                    "POSTGRES_USER": f"{self.project_name}_user",
                    "POSTGRES_PASSWORD": postgres_password,
                    "POSTGRES_DB": f"{self.project_name}_db",
                    "RABBITMQ_HOST": "rabbitmq",
                    "RABBITMQ_PORT": "5672",
                    "RABBITMQ_USER": f"{self.project_name}_user",
                    "RABBITMQ_PASSWORD": rabbitmq_password,
                }
            },
            "env_aliases": {},
        }

        # Add app-specific sections - NO HARDCODED APP NAMES!
        for app_name in app_names:
            passwords_config["secrets"][app_name] = {}
            passwords_config["env_aliases"][app_name] = {}

        # Generate secrets.yml with beautiful formatting
        secrets_yml = project_dir / "secrets.yml"

        yml_lines = []

        # Header
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(f"# {self.project_name} - Secrets Configuration")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(f"# Auto-generated by: superdeploy {self.project_name}:init")
        yml_lines.append(
            f"# Edit secrets, then run: superdeploy {self.project_name}:validate"
        )
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("#")
        yml_lines.append(
            "# ⚠️  SECURITY WARNING: This file contains sensitive credentials!"
        )
        yml_lines.append("#    - DO NOT commit this file to Git")
        yml_lines.append("#    - Keep restrictive file permissions (600)")
        yml_lines.append("#    - Store securely in password manager/vault")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("")

        # Shared Secrets Section
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# Shared Secrets")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# Available to all applications in this project")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("secrets:")
        yml_lines.append("  shared:")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append("    # Database Configuration (Auto-generated)")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append(
            "    POSTGRES_HOST: ''    # Auto-filled with VM internal IP after 'superdeploy project:up'"
        )
        yml_lines.append(
            f"    POSTGRES_PORT: '{passwords_config['secrets']['shared']['POSTGRES_PORT']}'"
        )
        yml_lines.append(
            f"    POSTGRES_USER: {passwords_config['secrets']['shared']['POSTGRES_USER']}"
        )
        yml_lines.append(
            f"    POSTGRES_PASSWORD: {passwords_config['secrets']['shared']['POSTGRES_PASSWORD']}"
        )
        yml_lines.append(
            f"    POSTGRES_DB: {passwords_config['secrets']['shared']['POSTGRES_DB']}"
        )
        yml_lines.append("")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append("    # Message Queue Configuration (Auto-generated)")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append(
            "    RABBITMQ_HOST: ''    # Auto-filled with VM internal IP after 'superdeploy project:up'"
        )
        yml_lines.append(
            f"    RABBITMQ_PORT: '{passwords_config['secrets']['shared']['RABBITMQ_PORT']}'"
        )
        yml_lines.append(
            f"    RABBITMQ_USER: {passwords_config['secrets']['shared']['RABBITMQ_USER']}"
        )
        yml_lines.append(
            f"    RABBITMQ_PASSWORD: {passwords_config['secrets']['shared']['RABBITMQ_PASSWORD']}"
        )
        yml_lines.append("")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append("    # Infrastructure")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append(
            "    ORCHESTRATOR_IP: ''  # Auto-filled after 'superdeploy orchestrator:up'"
        )
        yml_lines.append("")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append("    # Docker Registry Credentials")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append("    # Required for building and deploying container images")
        yml_lines.append(
            "    # Get token from: https://hub.docker.com/settings/security"
        )
        yml_lines.append("    DOCKER_REGISTRY: 'docker.io'  # Docker registry URL")
        yml_lines.append("    DOCKER_ORG: ''        # Docker Hub organization/username")
        yml_lines.append("    DOCKER_USERNAME: ''   # Your Docker Hub username")
        yml_lines.append(
            "    DOCKER_TOKEN: ''      # Docker Hub access token (NOT password)"
        )
        yml_lines.append("")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append("    # SMTP Configuration (Email Notifications)")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append("    # Optional: Used for system alerts and notifications")
        yml_lines.append(
            "    SMTP_HOST: 'smtp.gmail.com'  # Gmail SMTP (or use smtp.sendgrid.net, etc.)"
        )
        yml_lines.append(
            "    SMTP_PORT: '587'     # 587 (TLS), 465 (SSL), or 25 (plain)"
        )
        yml_lines.append(
            "    SMTP_USER: ''        # SMTP username (usually your email)"
        )
        yml_lines.append(
            "    SMTP_PASSWORD: ''    # SMTP password or app-specific password"
        )
        yml_lines.append("    SMTP_FROM: ''        # From email address")
        yml_lines.append("")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append("    # GitHub Integration (REQUIRED)")
        yml_lines.append("    # " + "-" * 73)
        yml_lines.append(
            "    # GitHub Personal Access Token for CI/CD and runner management"
        )
        yml_lines.append("    # Get token from: https://github.com/settings/tokens")
        yml_lines.append(
            "    # Required scopes: repo, workflow, admin:org (manage_runners)"
        )
        yml_lines.append(
            "    GITHUB_TOKEN: ''           # GitHub Personal Access Token (REQUIRED)"
        )
        yml_lines.append("    #   This token is used to:")
        yml_lines.append("    #   - Push code to private repositories")
        yml_lines.append("    #   - Trigger GitHub Actions workflows")
        yml_lines.append("    #   - Auto-generate runner registration tokens via API")
        yml_lines.append("")

        # App-Specific Secrets Section
        yml_lines.append("  # " + "=" * 75)
        yml_lines.append("  # Application-Specific Secrets")
        yml_lines.append("  # " + "=" * 75)
        yml_lines.append(
            "  # Add secrets that are only needed by specific applications"
        )
        yml_lines.append("  # Example: API_KEY: 'xyz123', STRIPE_SECRET: 'sk_test_...'")
        yml_lines.append("  # " + "=" * 75)
        for app_name in app_names:
            yml_lines.append(f"  {app_name}: {{}}")
        yml_lines.append("")

        # Environment Aliases Section
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("# Environment Variable Aliases")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append(
            "# Map framework-specific variable names to secrets defined above"
        )
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("#")
        yml_lines.append("# Format:")
        yml_lines.append("#   ALIAS_NAME: SECRET_NAME")
        yml_lines.append("#")
        yml_lines.append("# Rules:")
        yml_lines.append(
            "#   - UPPERCASE value = reference to secret (e.g., DB_HOST: POSTGRES_HOST)"
        )
        yml_lines.append(
            "#   - lowercase/mixed = static value (e.g., API_URL: http://10.1.0.2:8000)"
        )
        yml_lines.append("#")
        yml_lines.append("# Examples:")
        yml_lines.append("#")
        yml_lines.append("#   Python/Cara Framework:")
        yml_lines.append("#     DB_HOST: POSTGRES_HOST")
        yml_lines.append("#     DB_PORT: POSTGRES_PORT")
        yml_lines.append("#     DB_USERNAME: POSTGRES_USER")
        yml_lines.append("#     DB_PASSWORD: POSTGRES_PASSWORD")
        yml_lines.append("#     DB_DATABASE: POSTGRES_DB")
        yml_lines.append("#")
        yml_lines.append("#   Next.js:")
        yml_lines.append("#     NEXT_PUBLIC_API_URL: http://10.1.0.2:8000")
        yml_lines.append("#     DATABASE_URL: POSTGRES_HOST")
        yml_lines.append("# " + "=" * 77)
        yml_lines.append("env_aliases:")
        for app_name in app_names:
            yml_lines.append(f"  {app_name}: {{}}")
        yml_lines.append("")

        with open(secrets_yml, "w") as f:
            f.write("\n".join(yml_lines))

        # Set restrictive permissions
        secrets_yml.chmod(0o600)

        self.console.print(
            f"[dim]✓ Created: {secrets_yml.relative_to(project_root)}[/dim]"
        )
        self.console.print(
            "[dim]  Generated secure passwords for PostgreSQL and RabbitMQ[/dim]"
        )
        self.console.print(
            "[yellow]  ⚠ Fill in Docker, GitHub, and SMTP credentials before deploying![/yellow]"
        )

        # Summary
        self.console.print("\n[white]Next steps:[/white]")
        self.console.print(
            "  [dim]1. Edit secrets: nano projects/{}/secrets.yml[/dim]".format(
                self.project_name
            )
        )
        self.console.print(
            "     [yellow]→ Add DOCKER_ORG, DOCKER_USERNAME, DOCKER_TOKEN (required)[/yellow]"
        )
        self.console.print(
            "     [yellow]→ Add GITHUB_TOKEN (required - with admin:org scope)[/yellow]"
        )
        self.console.print(
            "     [yellow]→ Add SMTP credentials (optional, for email notifications)[/yellow]"
        )
        self.console.print(
            "  [dim]2. Generate deployment files: superdeploy {}:generate[/dim]".format(
                self.project_name
            )
        )
        self.console.print(
            "  [dim]3. Deploy infrastructure: superdeploy {}:up[/dim]\n".format(
                self.project_name
            )
        )


@click.command(name="init")
@click.option("--verbose", "-v", is_flag=True, help="Show all command output")
def init(project, verbose):
    """
    Initialize new project with secrets.yml

    Creates:
    - config.yml (infrastructure config)
    - secrets.yml (secret management)

    No more .env files!
    """
    cmd = InitCommand(project, verbose=verbose)
    cmd.run()
