name: Deploy Cheapa Storefront

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image with tag'
        required: true
        type: string
      env_bundle:
        description: 'Environment variables bundle (base64 encoded, PLAIN TEXT)'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA'
        required: true
        type: string
      git_ref:
        description: 'Git ref (branch/tag)'
        required: false
        default: 'production'
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, cheapa, app]
    steps:
      - name: Checkout superdeploy repo
        uses: actions/checkout@v4
        with:
          repository: cradexco/superdeploy
          ref: master
      
      - name: Deploy to VM
        uses: ./.forgejo/actions/deploy
        with:
          project: cheapa
          service: storefront
          image: ${{ inputs.image }}
          env_bundle: ${{ inputs.env_bundle }}
          git_sha: ${{ inputs.git_sha }}
          git_ref: ${{ inputs.git_ref }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
