name: Deploy Cheapa API

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image with tag'
        required: true
        type: string
      env_bundle:
        description: 'AGE-encrypted environment variables bundle (base64 encoded)'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA'
        required: true
        type: string
      git_ref:
        description: 'Git ref (branch/tag)'
        required: false
        default: 'production'
        type: string

jobs:
  deploy:
    uses: ./.forgejo/workflows/reusable/deploy-service.yml
    with:
      project: cheapa
      service: api
      port: "8000"
      image: ${{ inputs.image }}
      env_bundle: ${{ inputs.env_bundle }}
      git_sha: ${{ inputs.git_sha }}
      git_ref: ${{ inputs.git_ref }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
