name: Deploy Cheapa Api

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image with tag'
        required: true
        type: string
      env_bundle:
        description: 'AGE-encrypted environment variables bundle (base64 encoded)'
        required: true
        type: string
      git_sha:
        description: 'Git commit SHA'
        required: true
        type: string
      git_ref:
        description: 'Git ref (branch/tag)'
        required: false
        default: 'production'
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, cheapa, app]
    
    steps:
      - name: Check age installation
        run: |
          if command -v age &> /dev/null; then
            echo "✅ age already installed ($(age --version))"
          else
            echo "📥 Installing age..."
            curl -sL https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz | tar xz
            sudo mv age/age /usr/local/bin/
            rm -rf age
            echo "✅ age installed ($(age --version))"
          fi
      
      - name: Decode env bundle
        run: |
          echo "📦 Decoding environment bundle..."
          echo "${{ inputs.env_bundle }}" | base64 -d > /tmp/encrypted.age
          SIZE=$(wc -c < /tmp/encrypted.age)
          echo "✅ Decoded: $SIZE bytes"
      
      - name: Decrypt with AGE
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
        run: |
          echo "🔐 Decrypting with AGE..."
          
          if [ -z "$AGE_SECRET_KEY" ]; then
            echo "❌ AGE_SECRET_KEY not set!"
            exit 1
          fi
          
          printf '%s' "$AGE_SECRET_KEY" > /tmp/age-key.txt
          chmod 600 /tmp/age-key.txt
          
          if ! age -d -i /tmp/age-key.txt /tmp/encrypted.age > /tmp/decrypted.env 2>&1; then
            echo "❌ Decryption failed!"
            cat /tmp/decrypted.env || true
            rm -f /tmp/age-key.txt /tmp/encrypted.age /tmp/decrypted.env
            exit 1
          fi
          
          rm -f /tmp/age-key.txt /tmp/encrypted.age
          
          if [ ! -s /tmp/decrypted.env ]; then
            echo "❌ Decrypted file is empty!"
            exit 1
          fi
          
          SIZE=$(wc -c < /tmp/decrypted.env)
          echo "✅ Decrypted: $SIZE bytes"
      
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "🔑 Logging in to Docker Hub..."
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
          echo "✅ Logged in"
      
      - name: Pull Docker image
        run: |
          echo "📥 Pulling: ${{ inputs.image }}"
          docker pull ${{ inputs.image }}
          echo "✅ Image pulled"
      
      - name: Generate Docker Compose file
        run: |
          echo "📝 Generating docker-compose.yml..."
          
          PROJECT="cheapa"
          SERVICE="api"
          IMAGE="${{ inputs.image }}"
          PORT="8000"
          GIT_SHA="${{ inputs.git_sha }}"
          
          sudo mkdir -p /opt/apps/$PROJECT/compose
          
          cat > /tmp/docker-compose-$SERVICE.yml << 'DOCKERCOMPOSEEOF'
          services:
            SERVICE_PLACEHOLDER:
              image: IMAGE_PLACEHOLDER
              container_name: CONTAINER_PLACEHOLDER
              restart: unless-stopped
              env_file:
                - /tmp/decrypted.env
              networks:
                - NETWORK_PLACEHOLDER
              ports:
                - "PORT_PLACEHOLDER:PORT_PLACEHOLDER"
              labels:
                - "project=PROJECT_PLACEHOLDER"
                - "service=SERVICE_PLACEHOLDER"
                - "git.sha=GIT_SHA_PLACEHOLDER"
          
          networks:
            NETWORK_PLACEHOLDER:
              name: NETWORK_PLACEHOLDER
              external: true
          DOCKERCOMPOSEEOF
          
          # Replace placeholders
          sed -i "s/SERVICE_PLACEHOLDER/$SERVICE/g" /tmp/docker-compose-$SERVICE.yml
          sed -i "s/PROJECT_PLACEHOLDER/$PROJECT/g" /tmp/docker-compose-$SERVICE.yml
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" /tmp/docker-compose-$SERVICE.yml
          sed -i "s/CONTAINER_PLACEHOLDER/$PROJECT-$SERVICE/g" /tmp/docker-compose-$SERVICE.yml
          sed -i "s/NETWORK_PLACEHOLDER/$PROJECT-network/g" /tmp/docker-compose-$SERVICE.yml
          sed -i "s/PORT_PLACEHOLDER/$PORT/g" /tmp/docker-compose-$SERVICE.yml
          sed -i "s/GIT_SHA_PLACEHOLDER/$GIT_SHA/g" /tmp/docker-compose-$SERVICE.yml
          
          sudo mv /tmp/docker-compose-$SERVICE.yml /opt/apps/$PROJECT/compose/
          echo "✅ Compose file created"
      
      - name: Deploy with zero-downtime
        run: |
          echo "🚀 Deploying api (zero-downtime)..."
          
          cd /opt/apps/cheapa/compose
          
          CONTAINER_NAME="cheapa-api"
          NEW_CONTAINER="${CONTAINER_NAME}-new-$$"
          TEMP_PORT=$(expr 8000 + 10000)  # Temporary port for new container
          
          # Clean up any old temp containers first
          echo "🧹 Cleaning up old temp containers..."
          docker ps -a --filter "name=${CONTAINER_NAME}-new-" -q | xargs -r docker rm -f 2>/dev/null || true
          
          # Create temporary compose file with new container name and temp port
          sed -e "s/container_name: $CONTAINER_NAME/container_name: $NEW_CONTAINER/" -e 's/- "8000:8000"/- "'$TEMP_PORT':8000'"/' docker-compose-api.yml > /tmp/docker-compose-new-api.yml
          
          # Debug: show what was changed
          echo "📝 Checking port mapping..."
          grep "ports:" -A 1 /tmp/docker-compose-new-api.yml
          
          echo "🐳 Starting new container: $NEW_CONTAINER (temp port: $TEMP_PORT)"
          docker compose -f /tmp/docker-compose-new-api.yml up -d
          
          # Wait for container to start
          echo "⏳ Waiting for container to be ready..."
          sleep 5
          
          # Check if new container is running
          if [ -n "$(docker ps -q --filter "name=$NEW_CONTAINER")" ]; then
            echo "✅ New container is running"
            
            # Check health (wait up to 30s)
            for i in {1..6}; do
              HEALTH=$(docker inspect $NEW_CONTAINER 2>/dev/null | grep -o '"Status":"[^"]*"' | grep Health | cut -d'"' -f4 || echo "none")
              if [ "$HEALTH" = "healthy" ] || [ "$HEALTH" = "none" ]; then
                echo "✅ Health check passed (status: $HEALTH)"
                break
              fi
              echo "⏳ Waiting for health check... ($i/6)"
              sleep 5
            done
            
            # Stop and remove old container
            echo "⏸️  Stopping old container..."
            docker stop $CONTAINER_NAME 2>/dev/null || true
            docker rm $CONTAINER_NAME 2>/dev/null || true
            
            # Stop temp container (it's on temp port)
            echo "🔄 Recreating container on correct port..."
            docker stop $NEW_CONTAINER 2>/dev/null || true
            docker rm $NEW_CONTAINER 2>/dev/null || true
            
            # Start with original compose (correct port and name)
            docker compose -f docker-compose-api.yml up -d
            
            echo "✅ Zero-downtime deployment complete!"
          else
            echo "❌ New container failed to start"
            docker stop $NEW_CONTAINER 2>/dev/null || true
            docker rm $NEW_CONTAINER 2>/dev/null || true
            exit 1
          fi
          
          # Cleanup temp file
          rm -f /tmp/docker-compose-new-api.yml
      
      - name: Show container status
        run: |
          echo "📊 Container status:"
          docker ps --filter "name=cheapa-api"
      
      - name: Cleanup
        if: always()
        run: |
          rm -f /tmp/decrypted.env /tmp/encrypted.age /tmp/age-key.txt
          echo "🧹 Cleanup complete"
