generated_at: '2025-10-22T12:49:03.822779'
note: Add these to GitHub Secrets for each app repository
passwords:
  POSTGRES_PASSWORD: SGyU-4kj6pPppzblhZesu8LtwuaGO0NXUZOGM760E_A
  RABBITMQ_PASSWORD: AFdeeHYDsk205XBjbfsDrQjuXSJbF84w6VaDTjWKpxk
  REDIS_PASSWORD: 9P7yFkk2KYhqSHA14IQ4kitwAf45o1rmRpjSHGg0PvU
