"""Orchestrator secret management - DB-based"""

from pathlib import Path
from typing import Dict, Any


class OrchestratorSecretManager:
    """Manages orchestrator secrets - now DB-based (no files)"""

    def __init__(self, shared_dir: Path):
        self.shared_dir = Path(shared_dir)
        # No more secrets_file - everything in database

    def _get_project_id(self, db) -> int:
        """Get orchestrator project ID from database."""
        from cli.database import Project

        project = db.query(Project).filter(Project.name == "orchestrator").first()
        return project.id if project else None

    def load_secrets(self) -> Dict[str, Any]:
        """Load orchestrator secrets from database"""
        from cli.database import get_db_session, Secret

        db = get_db_session()
        try:
            project_id = self._get_project_id(db)
            if not project_id:
                return {"secrets": {}}

            secrets = db.query(Secret).filter(Secret.project_id == project_id).all()

            # Return in format expected by Ansible vars
            result = {"secrets": {}}
            for secret in secrets:
                result["secrets"][secret.key] = secret.value

            return result
        finally:
            db.close()

    def save_secrets(self, secrets: Dict[str, Any]):
        """Save secrets to database (no files)"""
        from cli.database import get_db_session, Secret
        from datetime import datetime

        db = get_db_session()
        try:
            project_id = self._get_project_id(db)
            if not project_id:
                return

            secrets_data = secrets.get("secrets", {})

            for key, value in secrets_data.items():
                # Update or insert
                existing = (
                    db.query(Secret)
                    .filter(
                        Secret.project_id == project_id,
                        Secret.key == key,
                    )
                    .first()
                )

                if existing:
                    existing.value = value
                    existing.updated_at = datetime.utcnow()
                else:
                    new_secret = Secret(
                        project_id=project_id,
                        app_id=None,
                        key=key,
                        value=value,
                        environment="production",
                        source="generated",
                        editable=True,
                        created_at=datetime.utcnow(),
                        updated_at=datetime.utcnow(),
                    )
                    db.add(new_secret)

            db.commit()
        finally:
            db.close()

    def initialize_secrets(self) -> Dict[str, str]:
        """Load secrets from database (already generated by orchestrator:init)"""
        secrets_data = self.load_secrets()

        # If secrets already exist in DB, return them
        if secrets_data.get("secrets"):
            return secrets_data["secrets"]

        # No secrets found - this shouldn't happen if orchestrator:init was run
        return {}

    def get_secret(self, key: str) -> str:
        """Get specific secret from database"""
        from cli.database import get_db_session, Secret

        db = get_db_session()
        try:
            project_id = self._get_project_id(db)
            if not project_id:
                return ""

            secret = (
                db.query(Secret)
                .filter(
                    Secret.project_id == project_id,
                    Secret.key == key,
                )
                .first()
            )
            return secret.value if secret else ""
        finally:
            db.close()

    def add_secret(self, key: str, value: str):
        """Add or update secret in database"""
        secrets_data = {"secrets": {key: value}}
        self.save_secrets(secrets_data)

    def get_all_secrets(self) -> Dict[str, str]:
        """Get all secrets from database"""
        secrets_data = self.load_secrets()
        return secrets_data.get("secrets", {})
