"""Project config.yml template generator"""

import yaml
from datetime import datetime


def generate_project_config(
    project_name: str,
    gcp_project: str,
    gcp_region: str,
    github_org: str,
    apps: dict,
) -> str:
    """Generate formatted project config.yml content"""

    project_config = {
        "project": {
            "name": project_name,
            "description": f"{project_name} project",
            "created_at": datetime.now().isoformat(),
            "ssl_email": f"admin@{project_name}.io",
        },
        "cloud": {
            "gcp": {
                "project_id": gcp_project,
                "region": gcp_region,
                "zone": f"{gcp_region}-a",
            },
            "ssh": {
                "key_path": "~/.ssh/superdeploy_deploy",
                "public_key_path": "~/.ssh/superdeploy_deploy.pub",
                "user": "superdeploy",
            },
        },
        "vms": {
            "core": {
                "count": 1,
                "machine_type": "e2-medium",
                "disk_size": 20,
                "services": ["rabbitmq", "postgres"],
            },
            "app": {
                "count": 1,
                "machine_type": "e2-medium",
                "disk_size": 30,
                "services": [],
            },
        },
        "addons": {
            "rabbitmq": {"version": "3.12-management-alpine"},
            "postgres": {"version": "15-alpine"},
            "caddy": {"version": "2-alpine"},
        },
        "apps": apps,
        "docker": {
            "registry": "docker.io",
            "organization": "your-docker-org",
        },
        "github": {"organization": github_org},
        "network": {
            "vpc_subnet": "10.1.0.0/16",
            "docker_subnet": "172.30.0.0/24",
        },
    }

    # Build formatted YAML with comments
    yml_lines = []
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(f"# {project_name} - Project Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(f"# Auto-generated by: superdeploy {project_name}:init")
    yml_lines.append(f"# Edit this file, then run: superdeploy {project_name}:generate")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("")
    yml_lines.append("# Project Information")
    yml_lines.append(
        yaml.dump(
            {"project": project_config["project"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Cloud Provider Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"cloud": project_config["cloud"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# VMs (Infrastructure)")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"vms": project_config["vms"]}, default_flow_style=False, sort_keys=False
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Addons Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"addons": project_config["addons"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Application Services")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Each app can specify:")
    yml_lines.append(
        "#   type: Application type (python, nextjs) - optional, auto-detected"
    )
    yml_lines.append("#   replicas: Number of container instances (default: 1)")
    yml_lines.append("#   path: Path to application source code")
    yml_lines.append("#   vm: VM role to deploy to")
    yml_lines.append("#   port: HTTP port for the application (optional for workers)")
    yml_lines.append("#   domain: Custom domain (optional)")
    yml_lines.append("#   addons: List of addon connections")
    yml_lines.append("#   hooks: Post-deployment commands (optional)")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"apps": project_config["apps"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Docker Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"docker": project_config["docker"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# GitHub Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"github": project_config["github"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Network Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(
        yaml.dump(
            {"network": project_config["network"]},
            default_flow_style=False,
            sort_keys=False,
        ).strip()
    )
    yml_lines.append("")

    return "\n".join(yml_lines)
