"""Project secrets.yml template generator with addon support"""

import secrets
import string


def _generate_password(length: int = 43) -> str:
    """Generate a secure random password."""
    alphabet = string.ascii_letters + string.digits + "_-"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def generate_project_secrets(
    project_name: str,
    app_names: list,
    addons: dict = None,
    **kwargs,  # postgres_password, rabbitmq_password for backward compat
) -> str:
    """
    Generate formatted project secrets.yml content with addon support.

    Args:
        project_name: Project name
        app_names: List of app names
        addons: Dict of addons from config.yml (new format)
        **kwargs: Legacy parameters (ignored)
    """
    yml_lines = []
    addons = addons or {}

    # Check if orchestrator is already deployed and get its IP
    orchestrator_ip = ""
    try:
        from pathlib import Path

        # Assume we're in cli/stubs/configs/, go up to superdeploy root
        current_file = Path(__file__).resolve()
        superdeploy_root = current_file.parent.parent.parent.parent
        orchestrator_state_file = (
            superdeploy_root / "shared" / "orchestrator" / "state.yml"
        )

        if orchestrator_state_file.exists():
            import yaml

            with open(orchestrator_state_file, "r") as f:
                state = yaml.safe_load(f) or {}
                orchestrator_ip = state.get("orchestrator_ip", "")
    except Exception:
        # If anything fails, just leave it empty (safe fallback)
        pass

    # Header
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(f"# {project_name} - Secrets Configuration")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append(f"# Auto-generated by: superdeploy {project_name}:init")
    yml_lines.append(f"# Edit secrets, then run: superdeploy {project_name}:validate")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("#")
    yml_lines.append("# ⚠️  SECURITY WARNING: This file contains sensitive credentials!")
    yml_lines.append("#    - DO NOT commit this file to Git")
    yml_lines.append("#    - Keep restrictive file permissions (600)")
    yml_lines.append("#    - Store securely in password manager/vault")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("")

    # Shared Secrets Section
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Shared Secrets")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Available to all applications in this project")
    yml_lines.append("# Format: secrets.shared.KEY_NAME")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("secrets:")
    yml_lines.append("  shared:")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Infrastructure")
    yml_lines.append("    # " + "-" * 73)

    # Auto-fill orchestrator IP if available
    if orchestrator_ip:
        yml_lines.append(
            f"    ORCHESTRATOR_IP: '{orchestrator_ip}'  # Auto-filled from orchestrator deployment"
        )
    else:
        yml_lines.append(
            "    ORCHESTRATOR_IP: ''  # Auto-filled after 'superdeploy orchestrator:up'"
        )

    yml_lines.append("")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Docker Registry Credentials")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Required for building and deploying container images")
    yml_lines.append("    # Get token from: https://hub.docker.com/settings/security")
    yml_lines.append("    DOCKER_REGISTRY: 'docker.io'  # Docker registry URL")
    yml_lines.append("    DOCKER_ORG: ''        # Docker Hub organization/username")
    yml_lines.append("    DOCKER_USERNAME: ''   # Your Docker Hub username")
    yml_lines.append(
        "    DOCKER_TOKEN: ''      # Docker Hub access token (NOT password)"
    )
    yml_lines.append("")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # SMTP Configuration (Email Notifications)")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # Optional: Used for system alerts and notifications")
    yml_lines.append(
        "    SMTP_HOST: 'smtp.gmail.com'  # Gmail SMTP (or use smtp.sendgrid.net, etc.)"
    )
    yml_lines.append("    SMTP_PORT: '587'     # 587 (TLS), 465 (SSL), or 25 (plain)")
    yml_lines.append("    SMTP_USER: ''        # SMTP username (usually your email)")
    yml_lines.append(
        "    SMTP_PASSWORD: ''    # SMTP password or app-specific password"
    )
    yml_lines.append("    SMTP_FROM: ''        # From email address")
    yml_lines.append("")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append("    # GitHub Integration (REQUIRED)")
    yml_lines.append("    # " + "-" * 73)
    yml_lines.append(
        "    # GitHub Personal Access Token for CI/CD and runner management"
    )
    yml_lines.append("    # Get token from: https://github.com/settings/tokens")
    yml_lines.append(
        "    # Required scopes: repo, workflow, admin:org (manage_runners)"
    )
    yml_lines.append(
        "    GITHUB_TOKEN: ''           # GitHub Personal Access Token (REQUIRED)"
    )
    yml_lines.append("    #   This token is used to:")
    yml_lines.append("    #   - Push code to private repositories")
    yml_lines.append("    #   - Trigger GitHub Actions workflows")
    yml_lines.append("    #   - Auto-generate runner registration tokens via API")
    yml_lines.append("")
    yml_lines.append(
        "    PRIVATE_REPO_TOKEN: ''     # GitHub PAT for private repo access in workflows"
    )
    yml_lines.append("    #   Required scope: repo (full control of private repos)")
    yml_lines.append("    #   Used by GitHub Actions to checkout private repositories")
    yml_lines.append("")

    # Addon Secrets Section (UNDER secrets!)
    yml_lines.append("")
    yml_lines.append("  # " + "=" * 75)
    yml_lines.append("  # Addon Instance Credentials")
    yml_lines.append("  # " + "=" * 75)
    yml_lines.append("  # Format: secrets.addons.{ADDON_TYPE}.{INSTANCE_NAME}")
    yml_lines.append(
        "  # Example: secrets.addons.postgres.primary (NOT databases.primary)"
    )
    yml_lines.append("  # " + "=" * 75)
    yml_lines.append("  addons:")

    if addons:
        # Group instances by addon type
        addons_by_type = {}
        for category, instances in addons.items():
            for instance_name, instance_config in instances.items():
                addon_type = instance_config.get("type", "")
                if addon_type not in addons_by_type:
                    addons_by_type[addon_type] = {}
                addons_by_type[addon_type][instance_name] = {
                    "category": category,
                    "config": instance_config,
                }

        # Write grouped by addon type (indented under secrets)
        # Track port allocation per addon type
        port_counters = {}
        base_ports = {
            "postgres": 5432,
            "rabbitmq": 5672,
            "redis": 6379,
            "mongodb": 27017,
            "elasticsearch": 9200,
        }

        for addon_type in sorted(addons_by_type.keys()):
            yml_lines.append(f"    {addon_type}:")

            # Initialize port counter for this addon type
            if addon_type not in port_counters:
                port_counters[addon_type] = 0

            for instance_name, instance_data in sorted(
                addons_by_type[addon_type].items()
            ):
                category = instance_data["category"]
                full_name = f"{category}.{instance_name}"

                yml_lines.append(f"      {instance_name}:")

                # Generate credentials based on addon type (UPPERCASE keys!)
                if addon_type == "postgres":
                    yml_lines.append(f"        USER: {project_name}_user")
                    yml_lines.append(f"        PASSWORD: {_generate_password()}")
                    yml_lines.append(f"        DATABASE: {project_name}_db")
                    # HOST is container name in Docker network
                    yml_lines.append(f"        HOST: {project_name}_{addon_type}_{instance_name}")
                    # Auto-allocate port (5432, 5433, 5434, ...)
                    port = base_ports.get(addon_type, 5432) + port_counters[addon_type]
                    yml_lines.append(f"        PORT: '{port}'")
                    port_counters[addon_type] += 1

                elif addon_type == "rabbitmq":
                    yml_lines.append(f"        USER: {project_name}_user")
                    yml_lines.append(f"        PASSWORD: {_generate_password()}")
                    yml_lines.append("        VHOST: /")
                    # HOST is container name in Docker network
                    yml_lines.append(f"        HOST: {project_name}_{addon_type}_{instance_name}")
                    # Auto-allocate ports (5672, 5673, ...)
                    port = base_ports.get(addon_type, 5672) + port_counters[addon_type]
                    mgmt_port = 15672 + port_counters[addon_type]
                    yml_lines.append(f"        PORT: '{port}'")
                    yml_lines.append(f"        MANAGEMENT_PORT: '{mgmt_port}'")
                    port_counters[addon_type] += 1

                elif addon_type == "redis":
                    yml_lines.append(f"        PASSWORD: {_generate_password()}")
                    # HOST is container name in Docker network
                    yml_lines.append(f"        HOST: {project_name}_{addon_type}_{instance_name}")
                    port = base_ports.get(addon_type, 6379) + port_counters[addon_type]
                    yml_lines.append(f"        PORT: '{port}'")
                    port_counters[addon_type] += 1

                elif addon_type == "mongodb":
                    yml_lines.append(f"        USER: {project_name}_user")
                    yml_lines.append(f"        PASSWORD: {_generate_password()}")
                    yml_lines.append(f"        DATABASE: {project_name}_db")
                    yml_lines.append(f"        ROOT_PASSWORD: {_generate_password()}")
                    # HOST is container name in Docker network
                    yml_lines.append(f"        HOST: {project_name}_{addon_type}_{instance_name}")
                    port = base_ports.get(addon_type, 27017) + port_counters[addon_type]
                    yml_lines.append(f"        PORT: '{port}'")
                    port_counters[addon_type] += 1

                elif addon_type == "elasticsearch":
                    yml_lines.append("        USER: elastic")
                    yml_lines.append(f"        PASSWORD: {_generate_password()}")
                    # HOST is container name in Docker network
                    yml_lines.append(f"        HOST: {project_name}_{addon_type}_{instance_name}")
                    port = base_ports.get(addon_type, 9200) + port_counters[addon_type]
                    yml_lines.append(f"        PORT: '{port}'")
                    port_counters[addon_type] += 1

                elif addon_type == "caddy":
                    yml_lines.append("        HOST: ''  # Auto-filled by deployment")
                    port_http = 80 + (port_counters.get(addon_type, 0) * 10)
                    port_https = 443 + (port_counters.get(addon_type, 0) * 10)
                    yml_lines.append(f"        HTTP_PORT: '{port_http}'")
                    yml_lines.append(f"        HTTPS_PORT: '{port_https}'")
                    yml_lines.append("        ADMIN_PORT: '2019'")
                    port_counters[addon_type] = port_counters.get(addon_type, 0) + 1

                elif addon_type == "monitoring":
                    # Monitoring uses flat secrets (see orchestrator/secrets.yml)
                    yml_lines.append(
                        "        # Monitoring credentials in orchestrator/secrets.yml"
                    )

                else:
                    # Generic addon (assume user/password pattern)
                    yml_lines.append(f"        USER: {project_name}_user")
                    yml_lines.append(f"        PASSWORD: {_generate_password()}")
                    yml_lines.append("        HOST: ''  # Auto-filled by deployment")
                    yml_lines.append("        PORT: ''  # Set manually")

                yml_lines.append("")
    else:
        yml_lines.append("    # No addons configured")
        yml_lines.append("    # Add addon instances in config.yml first")
        yml_lines.append("")

    # App-Specific Secrets Section (UNDER secrets!)
    yml_lines.append("  # " + "=" * 75)
    yml_lines.append("  # Application-Specific Secrets")
    yml_lines.append("  # " + "=" * 75)
    yml_lines.append("  # Format: secrets.apps.{APP_NAME}.KEY_NAME")
    yml_lines.append("  # Example: secrets.apps.api.JWT_SECRET")
    yml_lines.append("  # " + "=" * 75)
    yml_lines.append("  apps:")
    for app_name in app_names:
        yml_lines.append(f"    {app_name}: {{}}")
    yml_lines.append("")

    # Environment Aliases Section
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Environment Variable Aliases")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("# Map framework-specific variable names to secrets defined above")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("#")
    yml_lines.append("# Format:")
    yml_lines.append("#   ALIAS_NAME: SECRET_PATH")
    yml_lines.append("#")
    yml_lines.append("# Rules:")
    yml_lines.append("#   - Uppercase reference: addons.databases.primary.user")
    yml_lines.append("#   - Static value: http://10.1.0.2:8000")
    yml_lines.append("#")
    yml_lines.append("# Examples:")
    yml_lines.append("#")
    yml_lines.append("#   Python/Cara Framework (using addon references):")
    yml_lines.append("#     DB_HOST: addons.databases.primary.host")
    yml_lines.append("#     DB_PORT: addons.databases.primary.port")
    yml_lines.append("#     DB_USERNAME: addons.databases.primary.user")
    yml_lines.append("#     DB_PASSWORD: addons.databases.primary.password")
    yml_lines.append("#     DB_DATABASE: addons.databases.primary.database")
    yml_lines.append("#")
    yml_lines.append("#     RABBITMQ_HOST: addons.queues.main.host")
    yml_lines.append("#     RABBITMQ_PORT: addons.queues.main.port")
    yml_lines.append("#     RABBITMQ_USER: addons.queues.main.user")
    yml_lines.append("#     RABBITMQ_PASSWORD: addons.queues.main.password")
    yml_lines.append("#")
    yml_lines.append("#   Next.js:")
    yml_lines.append("#     NEXT_PUBLIC_API_URL: http://10.1.0.2:8000")
    yml_lines.append("#     DATABASE_URL: addons.databases.primary.host")
    yml_lines.append("# " + "=" * 77)
    yml_lines.append("env_aliases:")
    for app_name in app_names:
        yml_lines.append(f"  {app_name}: {{}}")
    yml_lines.append("")

    return "\n".join(yml_lines)
