name: 'Send Deployment Notification'
description: 'Send email notification after deployment'
author: 'Superdeploy Team'

inputs:
  project:
    description: 'Project name'
    required: true
  service:
    description: 'Service name'
    required: true
  image:
    description: 'Docker image deployed'
    required: true
  status:
    description: 'Deployment status (success/failure)'
    required: true
    default: 'success'
  git_sha:
    description: 'Git commit SHA'
    required: true
  git_ref:
    description: 'Git ref (branch/tag)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send email notification
      shell: bash
      run: |
        set -e
        
        echo "📧 Sending deployment notification..."
        
        # Load environment variables for email config
        if [ -f /tmp/decrypted.env ]; then
          set -a
          source /tmp/decrypted.env
          set +a
        fi
        
        # Check if email is configured
        if [ -z "$ALERT_EMAIL" ]; then
          echo "⚠️  ALERT_EMAIL not configured, skipping notification"
          exit 0
        fi
        
        # Prepare notification details
        STATUS="${{ inputs.status }}"
        PROJECT="${{ inputs.project }}"
        SERVICE="${{ inputs.service }}"
        IMAGE="${{ inputs.image }}"
        GIT_SHA="${{ inputs.git_sha }}"
        GIT_REF="${{ inputs.git_ref }}"
        TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')
        
        if [ "$STATUS" = "success" ]; then
          SUBJECT="✅ Deployment Success: $PROJECT/$SERVICE"
          STATUS_EMOJI="✅"
        else
          SUBJECT="❌ Deployment Failed: $PROJECT/$SERVICE"
          STATUS_EMOJI="❌"
        fi
        
        # Install mailutils if not present
        if ! command -v mail &> /dev/null; then
          echo "📦 Installing mailutils..."
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -qq && sudo apt-get install -y mailutils postfix 2>&1 | grep -v "^Get:" || {
            echo "⚠️  Failed to install mailutils - email will be skipped"
            exit 0
          }
        fi
        
        # Get VM info
        HOSTNAME=$(hostname)
        VM_IP=$(hostname -I | awk '{print $1}')
        
        # Get service URL from environment
        SERVICE_PORT=""
        case "$SERVICE" in
          api) SERVICE_PORT="8000" ;;
          dashboard) SERVICE_PORT="3000" ;;
          services) SERVICE_PORT="8001" ;;
        esac
        
        # Send email with HTML formatting
        {
          echo "Content-Type: text/html; charset=UTF-8"
          echo "Subject: $SUBJECT"
          echo ""
          echo "<html><body style='font-family: Arial, sans-serif; color: #333;'>"
          echo "<h2 style='color: $([ "$STATUS" = "success" ] && echo "#28a745" || echo "#dc3545");'>$STATUS_EMOJI Deployment $STATUS</h2>"
          echo "<table style='border-collapse: collapse; width: 100%; max-width: 600px;'>"
          echo "<tr><td style='padding: 8px; border-bottom: 1px solid #ddd;'><strong>Project</strong></td><td style='padding: 8px; border-bottom: 1px solid #ddd;'>$PROJECT</td></tr>"
          echo "<tr><td style='padding: 8px; border-bottom: 1px solid #ddd;'><strong>Service</strong></td><td style='padding: 8px; border-bottom: 1px solid #ddd;'>$SERVICE</td></tr>"
          echo "<tr><td style='padding: 8px; border-bottom: 1px solid #ddd;'><strong>Image</strong></td><td style='padding: 8px; border-bottom: 1px solid #ddd;'><code>$IMAGE</code></td></tr>"
          echo "<tr><td style='padding: 8px; border-bottom: 1px solid #ddd;'><strong>VM</strong></td><td style='padding: 8px; border-bottom: 1px solid #ddd;'>$HOSTNAME ($VM_IP)</td></tr>"
          if [ -n "$SERVICE_PORT" ]; then
            echo "<tr><td style='padding: 8px; border-bottom: 1px solid #ddd;'><strong>URL</strong></td><td style='padding: 8px; border-bottom: 1px solid #ddd;'><a href='http://$VM_IP:$SERVICE_PORT'>http://$VM_IP:$SERVICE_PORT</a></td></tr>"
          fi
          echo "<tr><td style='padding: 8px; border-bottom: 1px solid #ddd;'><strong>Commit</strong></td><td style='padding: 8px; border-bottom: 1px solid #ddd;'><code>${GIT_SHA:0:8}</code> ($GIT_REF)</td></tr>"
          echo "<tr><td style='padding: 8px; border-bottom: 1px solid #ddd;'><strong>Time</strong></td><td style='padding: 8px; border-bottom: 1px solid #ddd;'>$TIMESTAMP</td></tr>"
          echo "</table>"
          echo "<p style='margin-top: 20px; font-size: 12px; color: #666;'>SuperDeploy automated notification</p>"
          echo "</body></html>"
        } | mail -a "Content-Type: text/html" -s "$SUBJECT" "$ALERT_EMAIL" 2>&1 && {
          echo "✅ Email sent to $ALERT_EMAIL"
        } || {
          echo "⚠️  Email send failed (not critical)"
        }
